Feature/qas card
bildvitta/asteroid pull request #1038
Opened 2024-02-06 22:32 UTC by felipejuzo02

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-02-07 13:07 UTC, eliasassuncao requested changes

2024-02-07 13:07 UTC, eliasassuncao commented on ui/src/components/card/QasCard.vue
> +    default: 'Ver mais'
eu acho que poderia ter um `expansionProps`, algo assim, pq irá ter 2 props pra o mesmo "componente", se futuramente tiver mais infos a serem passadas pra o expansion, vamos ter muitas props... Alinhar como time sobre isso.

2024-02-07 18:12 UTC, felipejuzo02 commented on ui/src/components/card/QasCard.vue
> +      </q-expansion-item>
Na vdd nao, pois tinha realizado algumas validações. Porém refiz essa parte pois realmente tinha ficado estranho, sendo que mesmo caso eu n tenha footer, ainda deixo em aberto pra usar ou nao o expansion, pois acho que algum produto pode querer usar somente o card, sem footer

2024-02-07 18:13 UTC, felipejuzo02 commented on ui/src/components/card/QasCard.vue
> +    default: 'Ver mais'
concordo com seu ponto, faz mais sentido uma unica

2024-02-07 21:59 UTC, eliasassuncao approved these changes

2024-02-07 21:59 UTC, eliasassuncao commented on docs/src/examples/QasCard/Basic.vue
> +        :route="{ name: 'Root'}"
faltou espaço a direita ` }`

2024-02-07 21:59 UTC, eliasassuncao commented on docs/src/examples/QasCard/Basic.vue
> +        :route="{ name: 'Root'}"
faltou espaço a direita ` }`

2024-02-07 21:59 UTC, eliasassuncao commented on ui/src/components/card/QasCard.vue
> +        <div class="full-width">
essa classe não poderia estar no expansion?

2024-02-08 12:24 UTC, gcarpi commented on ui/src/components/card/QasCard.vue
> +  const { getPaletteColor } = colors
Interessante isso ein, num conhecia

2024-02-08 12:25 UTC, gcarpi commented on ui/src/components/card/QasCard.vue
> +    text-decoration: none;
Você pode utilizar a classe `text-no-decoration` invés de colocar esse style

2024-02-08 12:25 UTC, gcarpi commented on ui/src/components/card/QasCard.yml
>  props:
Se puder colocar em ordem alfabética

2024-02-08 13:02 UTC, DouglasCalora requested changes

2024-02-08 13:02 UTC, DouglasCalora commented on ui/src/components/card/QasCard.vue
>    },
controlar pelo expansionProps

2024-02-08 21:38 UTC, eliasassuncao approved these changes

2024-02-09 12:40 UTC, gcarpi approved these changes

2024-02-20 20:27 UTC, DouglasCalora approved these changes

2024-02-20 20:27 UTC, DouglasCalora commented on CHANGELOG.md
> +
Acho que pode deixar isto mais claro:

```md
## Não publicado
## BREAKING CHANGES
-  `QasCard`: Componente agora se chama `QasCardImage`, pois agora foi criado um novo componente com o nome  de `QasCard` (`QasCard <-> QasCardImage`).

### Adicionado
- `QasCard` (novo): adicionado novo componente de card tendo o nome do antigo `QasCard`, pois este card não depende de imagens.

### Modificado
- `QasCard` (antigo): Alterado nome do componente para `QasCardImage`, uma vez que ele é um card com imagens.

2024-02-28 18:32 UTC, merged