Changes in QasBtnDropdown and QasActionsMenu
bildvitta/asteroid pull request #1065
Opened 2024-03-08 18:06 UTC by DouglasCalora

## Não publicado
## BREAKING CHANGES
- `QasBtnDropdown`:
  - removido propriedade `buttonProps`;
  - removido slot `left-button`.
- `QasActionsMenu`:
  - modificado comportamento, agora caso esteja usando a prop `splitName` e tenha 2 itens na lista, o componente deixará os botões um ao lado do outro.
  - antes o componente utilizava `QasBtnDropDown` quando tinha mais de 1 item e `QasBtn` quando tinha apenas 1 item, agora ele sempre utiliza o `QasBtnDropdown`.
  - propriedade `buttonProps` é aplicada quando o componente esta no modo "Opções", que é quando não utiliza o `splitName` ou esteja no `mobile`.
  - `QasActionsMenu`: removido propriedade `dropdownIcon`, uma vez que é possível passar pelo `buttonProps`.

### Adicionado
- `QasBtnDropdown`:
  - adicionado nova propriedade `buttonsPropsList`.
  - adicionado nova propriedade `disable`.
  - adicionado novo slot `bottom-[buttons-props-list-key]`.
- `QasActionsMenu`: adicionado nova propriedade `disable`.

### Modificado
- `QasBtnDropdown`: alterado componente para receber uma lista de botões.
- `QasActionsMenu`:
  - modificado comportamento, agora caso esteja usando a prop `splitName` e tenha 2 itens na lista, o componente deixará os botões um ao lado do outro.
  - antes o componente utilizava `QasBtnDropDown` quando tinha mais de 1 item e `QasBtn` quando tinha apenas 1 item, agora ele sempre utiliza o `QasBtnDropdown`.
  - propriedade `buttonProps` é aplicada quando o componente esta no modo "Opções", que é quando não utiliza o `splitName` ou esteja no `mobile`.

### Removido
- `QasBtnDropdown`:
  - removido propriedade `buttonProps`.
  - removido slot `left-button`.
- `QasActionsMenu`: removido propriedade `dropdownIcon`, uma vez que é possível passar pelo `buttonProps`.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [x] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [x] Sim
- [ ] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-03-08 19:56 UTC, eliasassuncao requested changes

2024-03-08 19:56 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/Basic.vue
> +}
pq não usar uma const só?

2024-03-08 19:56 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/ExDelete.vue
> +    </div>
precisa dessas divs? não dá pra usar só os actions-menu direto?

2024-03-08 19:56 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/ExDisable.vue
> +    </div>
o mesmo aqui

2024-03-08 19:56 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/ExSplit.vue
> +}
pq não usar só uma const?

2024-03-08 19:56 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/ExOptions.vue
> +}
pq não usar só uma const?

2024-03-08 19:56 UTC, eliasassuncao commented on ui/src/components/actions-menu/QasActionsMenu.vue
> +        <q-tooltip v-if="hasTooltip && item.label">
lógica na view

2024-03-08 19:56 UTC, eliasassuncao commented on ui/src/components/actions-menu/QasActionsMenu.vue
> +}
poderia ser `return props.useLabel && properties.label` ?

2024-03-11 16:21 UTC, DouglasCalora commented on docs/src/examples/QasActionsMenu/Basic.vue
> +}
Mais facil de testar no futuro

2024-03-11 16:21 UTC, DouglasCalora commented on docs/src/examples/QasActionsMenu/ExDelete.vue
> +    </div>
removido div

2024-03-11 16:21 UTC, DouglasCalora commented on docs/src/examples/QasActionsMenu/ExDisable.vue
> +    </div>
removido div

2024-03-11 16:25 UTC, DouglasCalora commented on ui/src/components/actions-menu/QasActionsMenu.vue
> +}
Não, ele retornaria um boolean false pro label caso não satisfizesse a condição

2024-04-04 16:25 UTC, merged