Feature/qas grid generator adjusts
bildvitta/asteroid pull request #1090
Opened 2024-04-18 18:00 UTC by eliasassuncao

### Adicionado
- `QasGridGenerator`: Adicionado prop `useEllipsis` que por default é `true`, que irá adicionar a classe `ellipsis` em seu conteúdo.
- `QasGridGenerator`: Adicionado prop `useInline` para mudar a disposição dos campos para ser por linha, ou seja, header e content ocupando a linha toda.

### Corrigido
- `QasGridGenerator`: Corrigido ao passar `col` na prop columns(`{ lg: 'col' }`).

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [x] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-04-18 20:11 UTC, DouglasCalora requested changes
Ver sobre o ellipsis

2024-04-18 20:11 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasGridGenerator`: Adicionado prop `useInline` para mudar a disposição dos campos para ser por linha, ou seja, header e content ocupando a linha toda.
- `QasGridGenerator`:
  - Adicionado prop `useEllipsis` com default é `true`, que irá adicionar a classe `ellipsis` em cada item do grid.`
  - Adicionado prop `useInline` para mudar a disposição dos campos para ser por linha, ou seja, header e content ocupando a linha toda.

2024-04-18 20:11 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasGridGenerator`: Corrigido ao passar `col` na prop columns(`{ lg: 'col' }`).
`QasGridGenerator`: Corrigido comportamento da propriedade `columns` quando passado com valores `col`, exemplo `{ lg: 'col' }`.

2024-04-18 20:11 UTC, DouglasCalora commented on docs/src/examples/QasGridGenerator/UseInline.vue
Adicionar exemplo ja em composition

2024-04-18 20:11 UTC, DouglasCalora commented on docs/src/pages/components/grid-generator.md
Adicione um `:::info` falando sobre o comportamento do `use-common-columns` com a prop columns por favor.

2024-04-18 20:11 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +  ellipsis: !screen.isSmall && props.useEllipsis
Não entendi o pq a validação pelo screen... normalmente o col no screen é 12

2024-04-18 20:11 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    <div v-for="(field, key) in fieldsByResult" :key="key" :class="getContainerClass({ key })">
o ellipsis não deveria englobar o label tb? label e result... todo o item

2024-04-18 20:11 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.yml
> +    desc: Utilizado quando passar a estrutura da prop "columns" sendo um objeto onde seus breakpoints serão replicados para todos fields.
`Usado quando precis apassar a prop "columns" como objeto sendo que será o valor comum para todos fields"

2024-04-18 20:42 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasGridGenerator`: Adicionado prop `useInline` para mudar a disposição dos campos para ser por linha, ou seja, header e content ocupando a linha toda.
feito

2024-04-18 20:43 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasGridGenerator`: Corrigido ao passar `col` na prop columns(`{ lg: 'col' }`).
feito

2024-04-18 20:46 UTC, eliasassuncao commented on docs/src/examples/QasGridGenerator/UseInline.vue
feito

2024-04-18 20:53 UTC, eliasassuncao commented on docs/src/pages/components/grid-generator.md
feito

2024-04-18 20:54 UTC, eliasassuncao commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +  ellipsis: !screen.isSmall && props.useEllipsis
pra não ter ellipsis no mobile q é oq alinhamos com o Vitor.

2024-04-18 20:57 UTC, eliasassuncao commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    <div v-for="(field, key) in fieldsByResult" :key="key" :class="getContainerClass({ key })">
as labels nunca irão ter conteúdo grande.

2024-04-18 20:58 UTC, eliasassuncao commented on ui/src/components/grid-generator/QasGridGenerator.yml
> +    desc: Utilizado quando passar a estrutura da prop "columns" sendo um objeto onde seus breakpoints serão replicados para todos fields.
feito

2024-04-18 21:07 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    <div v-for="(field, key) in fieldsByResult" :key="key" :class="getContainerClass({ key })">
Isto é uma afirmação forte, valide com o vitor por favor... pq se tiver não vai adiantar nada o ellipsis...

2024-04-19 14:31 UTC, DouglasCalora approved these changes
adc o uso do `title` no changelog

2024-04-19 14:31 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasGridGenerator`: Corrigido comportamento da propriedade `columns` quando passado com valores `col`, exemplo `{ lg: 'col' }`.
faltou falar sobre o `title`

2024-04-19 14:57 UTC, merged