QasSingleView: Composition and request changes.
bildvitta/asteroid pull request #1125
Opened 2024-06-24 21:26 UTC by DouglasCalora

## Não publicado
### Adicionado
- `QasSingleView`: Adicionado propriedade `use-store` para dar a possibilidade de utilizar o componente sem a store do vuex/pinia.

### Modificado
- `QasSingleView`:
  - modificado para composition API.
  - removido obrigatoriedade da propriedade "entity".

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-06-24 22:40 UTC, eliasassuncao requested changes

2024-06-24 22:40 UTC, eliasassuncao commented on ui/src/components/single-view/QasSingleView.vue
> +  ...emitList,
de onde tirou esse emitList? se tá no composable poderia ser `baseEmits` igual existe o `baseProps` ?

2024-06-24 22:40 UTC, eliasassuncao commented on ui/src/components/single-view/QasSingleView.vue
> +    const response = await getAction(payload)
não daria pra usar o promiseHandler?

2024-06-24 22:40 UTC, eliasassuncao commented on ui/src/components/single-view/QasSingleView.vue
> +  const { id: unusedID, url: unusedURL, ...externalPayload } = payload
oq é esse `unusedID` e `unusedURL` ?

2024-06-24 22:40 UTC, eliasassuncao commented on ui/src/composables/private/use-view.js
> +  const fetchErrorMessage = 'Ops… Não conseguimos acessar as informações. Por favor, tente novamente em alguns minutos.'
isso poderia externalizar pra gente de alguma forma, pq tem mt copy paste dessa mensagem nos produtos

2024-06-25 16:24 UTC, DouglasCalora commented on ui/src/components/single-view/QasSingleView.vue
> +  const { id: unusedID, url: unusedURL, ...externalPayload } = payload
renomeei pq ja existia esses valores... mas quando faço isto é pq não vou usar eles

2024-06-25 16:24 UTC, DouglasCalora commented on ui/src/composables/private/use-view.js
> +  const fetchErrorMessage = 'Ops… Não conseguimos acessar as informações. Por favor, tente novamente em alguns minutos.'
podemos pensar nisto como uma outra demanda, mas não neste PR.

2024-06-25 16:25 UTC, DouglasCalora commented on ui/src/components/single-view/QasSingleView.vue
> +  ...emitList,
Mas é no mesmo lugar, só não chama `baseEmits`, mudarei para `baseEmits`

2024-06-26 14:08 UTC, eliasassuncao approved these changes

2024-06-26 14:19 UTC, merged