feat: asteroid adjustments
bildvitta/asteroid pull request #1136
Opened 2024-07-30 17:49 UTC by felipejuzo02

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-07-30 18:47 UTC, DouglasCalora requested changes

2024-07-30 18:47 UTC, DouglasCalora commented on CHANGELOG.md
> +- [`QasFormView`, `QasListView`, `QasSingleView`]: adicionado novo slot chamado `error` que é disponibilizado quando ocorre o `fetchError`.
Faz mais sentido ser `fetch-error` e não error... o form-view por exemplo poderia ter um erro ao submit.

2024-07-30 18:47 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    return 'row justify-between full-width q-col-gutter-x-md q-pl-none'
Mas ficou fixo? e se eu passar outros gutters?

2024-07-30 18:47 UTC, DouglasCalora commented on ui/src/composables/private/use-view.js
> +  const isFetchError = ref(false)
hasFetchError

2024-07-30 18:47 UTC, DouglasCalora commented on ui/src/composables/private/use-view.js
> +  const canShowErrorSlot = computed(() => hasErrorSlot.value && isFetchError.value)
`canShowFetchErrorSlot`

2024-07-30 18:47 UTC, DouglasCalora commented on ui/src/mixins/view.js
> +    mx_canShowErrorSlot () {
`mx_canShowFetchErrorSlot`

2024-07-30 18:47 UTC, DouglasCalora commented on ui/src/mixins/view.js
> +      mx_isFetchError: false
`mx_hasFetchError`

2024-07-30 18:58 UTC, ErickGrCosta approved these changes

2024-07-30 19:01 UTC, eliasassuncao requested changes

2024-07-30 19:01 UTC, eliasassuncao commented on ui/src/components/list-view/QasListView.vue
> +          <slot v-if="mx_canShowFetchErrorSlot" name="fetch-error" />
comportamento está diferente do form-view não? exibe o erro junto com o conteúdo da pagina aqui, o form-view, não?

2024-07-30 19:01 UTC, eliasassuncao commented on ui/src/components/single-view/QasSingleView.vue
> +      <qas-empty-result-text v-else class="q-my-xl" />
pq este tem margin?

2024-07-30 19:05 UTC, felipejuzo02 commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    return 'row justify-between full-width q-col-gutter-x-md q-pl-none'
Ajustado de acordo com a props gutter (que por default é lg)

2024-07-30 19:07 UTC, felipejuzo02 commented on ui/src/components/form-view/QasFormView.vue
> +      <slot v-else />
Atualmente, caso haja erro, exibimos campos quebrado (pois os fields nao vem do back). O novo comportamente tem como intuito personalizar caso haja erro.

2024-07-30 19:10 UTC, felipejuzo02 commented on ui/src/components/list-view/QasListView.vue
> +          <slot v-if="mx_canShowFetchErrorSlot" name="fetch-error" />
O listView tem uma diferença do formView, que é caso de sucesso na request e nao tenha nada no retorno, é exibido uma mensagem de resultado vazio. Foi feito dentro desse contexto, pois quando da erro na request, necessariamente fica vazio os campos, entao mostra o texto q n encontrou, mas ai podemos personalizar nesses casos agr

2024-07-30 19:11 UTC, felipejuzo02 commented on ui/src/components/single-view/QasSingleView.vue
> +      <qas-empty-result-text v-else class="q-my-xl" />
Pois é apenas a mensagem de resultados n encontrados, no qual mantive apenas o antigo. O outro por ser slot, a responsabilidade fica pra quem usar o template dele

2024-07-31 17:15 UTC, eliasassuncao approved these changes

2024-07-31 17:20 UTC, merged