feat(QasSelectListDIalog): remove box inside box
bildvitta/asteroid pull request #1155
Opened 2024-08-16 21:46 UTC by felipejuzo02

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-08-20 20:04 UTC, DouglasCalora approved these changes

2024-08-20 20:04 UTC, DouglasCalora commented on docs/src/examples/QasInput/Counter.vue
> +
remover espaço

2024-08-20 20:05 UTC, eliasassuncao requested changes

2024-08-20 20:05 UTC, eliasassuncao commented on docs/src/examples/QasInput/Counter.vue
> +      </template>
pq foi adicionado isso? a intenção não é exibir o counter?

2024-08-20 20:05 UTC, eliasassuncao commented on ui/src/components/search-input/QasSearchInput.vue
> +  }
não tem ou deveria ter uma classe global pra esse estilo de borda?

2024-08-21 16:45 UTC, felipejuzo02 commented on ui/src/components/search-input/QasSearchInput.vue
> +  }
feito senhor

2024-08-21 17:59 UTC, DouglasCalora requested changes

2024-08-21 18:33 UTC, eliasassuncao approved these changes

2024-08-22 18:16 UTC, DouglasCalora approved these changes

2024-08-22 18:17 UTC, merged