Changes in `QasNestedFields`/`QasGridGenerator`/`QasFormGenerator`/`QasHeader`.
bildvitta/asteroid pull request #1171
Opened 2024-09-06 16:33 UTC by DouglasCalora

## BREAKING CHANGES
- `QasNestedFields`: agora propriedade `actions-menu-props` só funciona junto da prop `:use-inline-actions="true"`.

### Adicionado
- `QasNestedFields`: adicionado componente `QasHeader` com a prop `header-props`.

### Corrigido
- `QasActions`: corrigido style que não deixava div 100% quando usado com a prop `useFullWidth`.
- `QasNestedFields`: corrigido problemas de espaçamentos.
- `QasFormGenerator`: corrigido div vazia quando não tinha fieldset.
- `QasHeader`: corrigido problemas de layout.

### Modificado
- `QasDialog`:
  - alterado espaçamento interno de `lg` para `md`.
  - alterado titulo de h5 para h4 com componente `QasLabel`.
  - alterado espaçamento bottom do título de `lg` para `md`.
- [`QasFormGenerator`, `QasGridGenerator`]: alterado espaçamento gutter de `lg` para `md`.
- `QasNestedFields`:
  - modificado set scroll ao adicionado novas linhas, agora o scroll fica fixo na ultima linha adicionada.
  - agora propriedade `actions-menu-props` só funciona junto da prop `:use-inline-actions="true"`.
  - default do `formGutter` alterado de `lg` para `md`.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [x] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [x] Sim
- [ ] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-09-06 16:37 UTC, ErickGrCosta commented on docs/src/examples/QasNestedFields/NestedFieldsWithHeaderProps.vue
> +const model = ref([])
Precisaria entender melhor o que ele faz. Mas não poderia usar o defineModel?

2024-09-06 16:37 UTC, ErickGrCosta commented on docs/src/examples/QasNestedFields/NestedFieldsWithHeaderProps.vue
> +  formColumns: {
commonColumns?

2024-09-06 16:40 UTC, ErickGrCosta commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      const safeScrollSize = this.$qas.screen.isSmall ? 56 + SpacingWithNumber.Lg : SpacingWithNumber.Lg
56?

2024-09-06 16:40 UTC, ErickGrCosta approved these changes

2024-09-06 16:42 UTC, DouglasCalora commented on docs/src/examples/QasNestedFields/NestedFieldsWithHeaderProps.vue
> +const model = ref([])
Não, isto é uma pagina de documentação.

2024-09-06 16:43 UTC, DouglasCalora commented on docs/src/examples/QasNestedFields/NestedFieldsWithHeaderProps.vue
> +  formColumns: {
Não entendi... formColumns é a prop de columns repassadas

2024-09-06 16:43 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      const safeScrollSize = this.$qas.screen.isSmall ? 56 + SpacingWithNumber.Lg : SpacingWithNumber.Lg
Comentario acima, é o tamanho do header no mobile das nosas aplicações.

2024-09-06 16:56 UTC, felipejuzo02 requested changes

2024-09-06 16:56 UTC, felipejuzo02 commented on ui/src/components/form-generator/QasFormGenerator.vue
> +      __isFieldset: true
pq o __??

2024-09-06 16:56 UTC, felipejuzo02 commented on ui/src/components/nested-fields/QasNestedFields.vue
>            <template v-for="(row, index) in nested" :key="`row-${index}`">
vc poderia aproveitar a refatoracao do nested e colocar a key do row com o uid do quasar para poder usar animacao de ordenação, oq acha?

2024-09-06 16:56 UTC, felipejuzo02 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +        <div v-if="useAdd" :class="addButtonClass">
`addButtonClasses`

2024-09-06 16:56 UTC, felipejuzo02 commented on ui/src/enums/Spacing.js
> +}
só pr aconfirmar, criado esse enum pra usar em logicas js??

2024-09-06 17:16 UTC, DouglasCalora commented on ui/src/enums/Spacing.js
> +}
Também... mas pensa, amanha nós mudamos os tamanhos dos nossos espaçamentos e precisamos ficar entrcontrando onde usamos... dessa forma é só alterar aqui, sacou?

2024-09-06 17:16 UTC, DouglasCalora commented on ui/src/components/form-generator/QasFormGenerator.vue
> +      __isFieldset: true
despondido discord

2024-09-06 19:29 UTC, eliasassuncao approved these changes

2024-09-06 19:29 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
> +            typography: 'h5',
h5?

2024-09-06 20:30 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +            typography: 'h5',
Sim, alinhado com o rafa

2024-09-09 14:40 UTC, felipejuzo02 approved these changes

2024-09-09 17:23 UTC, merged