feat: "after" slot created
bildvitta/asteroid pull request #1180
Opened 2024-09-18 20:58 UTC by eliasassuncao

### Adicionado
- `QasFormGenerator`: criado slot `after`.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-09-18 20:59 UTC, ErickGrCosta approved these changes

2024-09-18 21:04 UTC, felipejuzo02 requested changes

2024-09-18 21:04 UTC, felipejuzo02 commented on CHANGELOG.md
> +- `QasFormGenerator`: criado slot `after`.
- `QasFormGenerator`: criado slot `after` por fieldset.

2024-09-18 21:04 UTC, felipejuzo02 commented on ui/src/components/form-generator/QasFormGenerator.vue
> +        <slot name="after" />
slot deveria ser por fieldset, nao geral

2024-09-19 12:36 UTC, felipejuzo02 approved these changes

2024-09-20 18:10 UTC, eliasassuncao commented on ui/src/components/form-generator/QasFormGenerator.vue
> +        <slot name="after" />
alinhado disc

2024-09-26 20:59 UTC, DouglasCalora requested changes

2024-09-26 20:59 UTC, DouglasCalora commented on CHANGELOG.md
> +## [Unreleased]
`## Não publicado`

2024-09-26 20:59 UTC, DouglasCalora commented on ui/src/components/form-generator/QasFormGenerator.vue
> +        <slot v-if="fieldsetItem.__isFieldset" :name="`after-${fieldsetItemKey}`" />
alterar para `legend-bottom-[nome-da-chave]`.

2024-09-26 20:59 UTC, DouglasCalora commented on ui/src/components/form-generator/QasFormGenerator.yml
> +  'after-[nome-da-chave]':
alterar para `legend-bottom-[nome-da-chave]`.

2024-09-27 13:21 UTC, eliasassuncao commented on CHANGELOG.md
> +## [Unreleased]
feito

2024-09-27 19:35 UTC, DouglasCalora approved these changes

2024-09-27 19:40 UTC, merged