Feature/issues
bildvitta/asteroid pull request #1184
Opened 2024-09-26 19:10 UTC by eliasassuncao

### Adicionado
- `QasTableGenerator`: adicionado componente `QasEmptyResultText` onde será exibido no caso dos valores da tabela serem vazios.
- `QasActionsMenu`: adicionado label `Opções` no botão splitted quando não for mobile.

### Modificado
- `QasExpansionItem`: modificado componente para ter uma borda caso esteja dentro de um `QasBox`.

### Modificado
- `QasDateTimeInput`: alterado o ícone do calendário.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-09-26 21:13 UTC, DouglasCalora requested changes

2024-09-26 21:13 UTC, DouglasCalora commented on CHANGELOG.md
> +## [Nao publicado]
Não tem `[]`

2024-09-26 21:13 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasActionsMenu`: adicionado label `Opções` no botão splitted quando não for mobile.
Não seria em modificado? adicionado normalmente são features que adc com props, eventos slots ou compoenntes novos...

2024-09-26 21:13 UTC, DouglasCalora commented on docs/src/examples/QasExpansionItem/WithBox.vue
> +defineOptions({ name: 'UsersList' })
name esta diferente do nome do arquivo

2024-09-26 21:13 UTC, DouglasCalora commented on docs/src/examples/QasExpansionItem/WithBox.vue
> +const result = ref({})
temos viewState para usar na documentação.

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    label: screen.isSmall ? '' : 'Opções'
Não entendi... não temos a prop `useLabelOnSmallScreen` pra isto??

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    ...(screen.isSmall ? { icon: props.dropdownIcon } : { iconRight: props.dropdownIcon }),
```js
[screen.isSmall ? 'icon' : 'iconRight]: props.dropdownIcon
``` 
O que acha dessa abordagem? senão gostou, cria uma const acima pra não poluir aqui...

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/expansion-item/QasExpansionItem.vue
> +const isNestedBox = inject('isBox', false)
entendo que fez o nome com a logica acima, porém neste caso não seria bem um nested... seria talvez `isInsideBox` mas precisa mesmo verificar o box? não é possível validar pelo isNestedExpansionItem??

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/expansion-item/QasExpansionItem.vue
> +})
```js
const boxProps = computed(() => {
  const isBoxed = !(isNestedBox && !isNestedExpansionItem)

  return {
    unelevated: isBoxed,
    outlined: isBoxed
  }
})
```

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/expansion-item/QasExpansionItem.vue
> +})
Continuar documentando o cóigo

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +      ellipsis: !screen.isSmall && hasEllipsis(field)
documentar no changelog em Corrigidos.

2024-09-26 21:13 UTC, DouglasCalora commented on ui/src/components/table-generator/QasTableGenerator.vue
> +        columns: this.hasResults ? this.columnsByFields : [],
não entendi a logica aqui, pq precisa disso?

2024-09-26 21:13 UTC, DouglasCalora commented on docs/src/examples/QasExpansionItem/WithBox.vue
> +})
melhor não usar computada assim pra não dar exemplo desta forma.

2024-09-26 21:15 UTC, felipejuzo02 approved these changes

2024-09-27 14:46 UTC, eliasassuncao commented on CHANGELOG.md
> +## [Nao publicado]
feito

2024-09-27 14:58 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasActionsMenu`: adicionado label `Opções` no botão splitted quando não for mobile.
feito

2024-09-27 18:56 UTC, eliasassuncao commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    label: screen.isSmall ? '' : 'Opções'
feito

2024-09-27 18:57 UTC, eliasassuncao commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    ...(screen.isSmall ? { icon: props.dropdownIcon } : { iconRight: props.dropdownIcon }),
feito

2024-09-27 18:58 UTC, eliasassuncao commented on ui/src/components/expansion-item/QasExpansionItem.vue
> +const isNestedBox = inject('isBox', false)
- mas é a mesma lógica do `isNestedExpansionItem `, pra saber se tem um expansion dentro de outro. 
- não, preciso saber se estou dentro de um `qas-box`, não dentro de um `expansion-item`

2024-09-27 19:12 UTC, eliasassuncao commented on ui/src/components/table-generator/QasTableGenerator.vue
> +        columns: this.hasResults ? this.columnsByFields : [],
se não fizer essa lógica, vai exibir os headers da tabela. Isso corrige aquele problema.

2024-09-27 19:12 UTC, eliasassuncao commented on docs/src/examples/QasExpansionItem/WithBox.vue
> +})
não entendi

2024-09-27 19:34 UTC, DouglasCalora approved these changes

2024-09-27 19:35 UTC, merged