feat(QasRadio/QasCheckbox): insert label
bildvitta/asteroid pull request #1210
Opened 2024-10-30 15:33 UTC by felipejuzo02

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-11-08 12:30 UTC, DouglasCalora requested changes

2024-11-08 12:30 UTC, DouglasCalora commented on docs/src/examples/QasExpansionItem/WithMaxContentHeight.vue
> +})
mantem no template msm neste caso pra n precisar de uma computada...

2024-11-08 12:30 UTC, DouglasCalora commented on ui/src/components/checkbox/QasCheckbox.vue
> +const singleAttrs = computed(() => {
singleAttributes.

2024-11-08 12:30 UTC, DouglasCalora commented on ui/src/components/checkbox/QasCheckbox.vue
> +const checkboxLabel = computed(() => props.label)
computada desnecessaria, só usar `props.label` onde precisar.

2024-11-08 12:30 UTC, DouglasCalora commented on ui/src/components/checkbox/QasCheckbox.yml
> +
remover um espaço

2024-11-08 12:30 UTC, DouglasCalora commented on ui/src/components/copy/QasCopy.yml
> +    desc: Controla se o texto vai ser exibido ou não no botão.
`ao lado do botão`.

2024-11-08 12:30 UTC, DouglasCalora commented on ui/src/components/radio/QasRadio.vue
> +const optionGroupLabel = computed(() => props.label)
computada desnecessaria, usar `props.label` onde precisar.

2024-11-08 19:49 UTC, felipejuzo02 commented on docs/src/examples/QasExpansionItem/WithMaxContentHeight.vue
> +})
aqui nao concordo, pq teria que passar na view:
```
:grid-generator-props="{fields: viewState.fields, result: viewState.result}"
```

2024-11-11 19:34 UTC, DouglasCalora approved these changes

2024-11-11 19:34 UTC, merged