Feature/uploader and stepper
bildvitta/asteroid pull request #1222
Opened 2024-12-12 18:09 UTC by felipejuzo02

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2024-12-17 18:44 UTC, eliasassuncao requested changes

2024-12-18 21:40 UTC, ErickGrCosta approved these changes

2024-12-20 12:10 UTC, felipejuzo02 commented on ui/src/components/stepper/QasStepper.vue
> +    <q-stepper ref="stepper" v-model="model" v-bind="stepperProps">
asteroid n quebramos linha entre as props

2024-12-20 12:18 UTC, felipejuzo02 commented on ui/src/components/uploader/QasUploader.vue
> +            </template>
![image](https://github.com/user-attachments/assets/2cca0799-0b96-4abf-a262-eb761aa3ac65)

2024-12-20 13:38 UTC, eliasassuncao approved these changes

2024-12-20 18:29 UTC, merged