Alteração no componente qas-tabs-generator
bildvitta/asteroid pull request #184
Opened 2021-03-29 21:03 UTC by leonardoMarco20

Closes #181

2021-03-29 21:16 UTC, caiotarifa requested changes

2021-03-29 21:16 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +      font-weight: bold;
Não é possível fazer isso apenas com as classes do Quasar? Sem usar CSS?

2021-03-29 21:16 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +  <q-tabs active-color="primary" class="tabs-generator" indicator-color="primary" v-model="currentTab" v-bind="$attrs" v-on="$listeners">
Favor lintar o código.

2021-03-30 00:56 UTC, DouglasCalora requested changes

2021-03-30 00:56 UTC, DouglasCalora commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +  <q-tabs active-color="primary" class="tabs-generator" indicator-color="primary" v-model="currentTab" v-bind="$attrs" v-on="$listeners">
Essa configuração de cor primary não deveria ser configuravel por prop e `primary` ser apenas o default? como faço se eu quiser mudar essa cor?

2021-03-30 00:56 UTC, DouglasCalora commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +.tabs-generator {
`qas-tabs-generator`

2021-03-30 00:56 UTC, DouglasCalora commented on CHANGELOG.md
> +### Changed
Não é desta forma, toda nova alteração é referente a uma nova versão, você colocou essa atualização dentro de uma versão antiga. Reveja o versionamento utilizando o [Semantic Versioning](https://semver.org/) e coloque os changed dentro desse versionamento.

2021-03-30 14:57 UTC, leonardoMarco20 commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +      font-weight: bold;
O q-tab não possui uma prop pra fazer esse tratamento. Sem falar que preciso tratar o q-tab__label do tab selecionado. Por isso precisei aplicar css aqui pessoal.

2021-03-30 14:59 UTC, leonardoMarco20 commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +  <q-tabs active-color="primary" class="tabs-generator" indicator-color="primary" v-model="currentTab" v-bind="$attrs" v-on="$listeners">
Criei 3 props, uma para cor geral da tab, uma para a cor da selecionada e outra para o indicador.

2021-03-30 15:00 UTC, leonardoMarco20 commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +.tabs-generator {
Corrigido

2021-03-30 15:00 UTC, leonardoMarco20 commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +  <q-tabs active-color="primary" class="tabs-generator" indicator-color="primary" v-model="currentTab" v-bind="$attrs" v-on="$listeners">
corrigido

2021-03-30 21:03 UTC, caiotarifa requested changes

2021-03-30 21:03 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +      type: String
Colocar em ordem alfabética conforme o padrão.

2021-03-30 21:03 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +      font-weight: bold;
`content-class` no QTab não resolve?

2021-03-31 12:34 UTC, leonardoMarco20 commented on ui/src/components/tabs-generator/QasTabsGenerator.vue
> +      font-weight: bold;
Dessa forma ele deixaria todas as labels com font-bold, a intenção é deixar apenas a selecionada. E para especificar a selecionada tive de fazer usando css, se não me engano qas-table-generator também faz dessa forma.

2021-04-01 13:26 UTC, DouglasCalora approved these changes

2021-04-01 13:34 UTC, caiotarifa approved these changes

2021-04-01 13:41 UTC, merged