Alterações no componente qas-uploader
bildvitta/asteroid pull request #186
Opened 2021-03-31 13:32 UTC by leonardoMarco20

Close #180

2021-03-31 14:37 UTC, caiotarifa requested changes

2021-03-31 17:18 UTC, leonardoMarco20 commented on CHANGELOG.md
> +### Changed
corrigido

2021-03-31 18:23 UTC, leonardoMarco20 commented on ui/src/components/uploader/QasUploader.vue
> +        <div class="cursor-pointer flex flex-center no-wrap q-gutter-xs q-pa-sm" @click="scope.pickFiles">
Corrigido

2021-04-02 03:55 UTC, caiotarifa approved these changes

2021-04-06 12:44 UTC, DouglasCalora approved these changes

2021-04-06 12:44 UTC, merged