Feature/qas dialog form validate
bildvitta/asteroid pull request #202
Opened 2021-04-09 17:30 UTC by hebertsilva

2021-04-09 18:18 UTC, caiotarifa approved these changes

2021-04-09 18:18 UTC, caiotarifa commented on ui/dev/src/pages/DialogForm.vue
> +<template>
**ATENÇÃO**
Eu sei que essa página é só de teste, fiz os comentários apenas pela oportunidade de explorar alguns conceitos. Caso tenha ciência do que eu disse, pode ignorar.

2021-04-09 18:18 UTC, caiotarifa commented on ui/dev/src/pages/DialogForm.vue
> +</style>
Usamos SCSS ao invés de SASS. E não encontrei onde essa classe foi usada.

2021-04-09 18:18 UTC, caiotarifa commented on ui/src/components/dialog/QasDialog.vue
> +      }
Uma outra forma de fazer isso é usar notação binária.

```this.useForm && this.$emit('validate', await this.$refs.form.validate())```

(Não precisa mudar, apenas para compartilhar uma opção.)

2021-04-09 18:26 UTC, hebertsilva commented on ui/dev/src/pages/DialogForm.vue
> +    <q-btn @click.native="showDialogForm = true">
Na verdade como é um file de teste eu estava usando uma tag `<p>`, ai ficou como lixo.

2021-04-09 18:28 UTC, hebertsilva commented on ui/dev/src/pages/DialogForm.vue
> +</style>
Esse também veio de lixo de `control+c` 😄

2021-04-09 18:29 UTC, hebertsilva commented on ui/dev/src/pages/DialogForm.vue
> +        <qas-input v-model="model.email" label="E-mail" :rules="[val => !!val || 'E-mail é obrigatório']" />
Sim, exemplo herdado direto do Quasar

2021-04-12 18:05 UTC, DouglasCalora requested changes

2021-04-12 18:05 UTC, DouglasCalora commented on ui/dev/src/pages/DialogForm.vue
> +</style>
E também remover o scoped

2021-04-12 18:05 UTC, DouglasCalora commented on ui/src/components/dialog/QasDialog.vue
> +      default: false,
Quando a prop é boolean o default já é `false` então não tem necessidade de definir um `default` apenas o `type`

2021-04-12 18:05 UTC, DouglasCalora commented on ui/src/components/dialog/QasDialog.vue
> +      }
@caiotarifa Inclusive é que utilizamos normalmente.

2021-04-12 18:37 UTC, caiotarifa approved these changes

2021-04-13 16:23 UTC, DouglasCalora approved these changes

2021-04-13 17:17 UTC, merged