Feature/qas text truncate
bildvitta/asteroid pull request #230
Opened 2021-04-22 16:59 UTC by leonardoMarco20

Close #207

2021-04-22 19:01 UTC, caiotarifa requested changes

2021-04-22 19:01 UTC, caiotarifa commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +    },
Importante falar que são as propriedades do QasDialog. Veja como fazemos esse tipo de referência nos outros componentes.

2021-04-22 19:01 UTC, caiotarifa commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +        component: 'Truncate a text depending that parent div width.'
`Truncate a text based on parent width.`

2021-04-22 20:57 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +    truncateText () {
Retornando como obj como ele seria interpretado no html? Ele retornaria apenas as classes onde a condição for true?

2021-04-22 20:57 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +      showDialog: false
corrigido

2021-04-22 20:57 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +import QasBtn from '../btn/QasBtn.vue'
corrigido

2021-04-22 20:57 UTC, leonardoMarco20 commented on CHANGELOG.md
> +- Added QasTextTruncate component in `ui/src/component`
adicionado

2021-04-22 21:06 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +        </div>
Se dialogTitle não for passado ele não será renderizado, mesmo assim precisaria desse v-if?

2021-04-22 21:07 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +      description: 'Width that will be used as a delimiter to create the truncate.'
corrigido

2021-04-22 21:08 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +      description: 'The text that will be show in the dialog.'
corrigido

2021-04-22 21:09 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +        component: 'Truncate a text depending that parent div width.'
corrigido

2021-04-23 14:19 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +      </template>
Ali o `#header` e `#description` são slots do dialog

2021-04-23 14:20 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +      <div v-if="hasTruncate" class="cursor-pointer text-primary" @click="toggleDialog">Ver mais</div>
feito

2021-04-23 16:32 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.stories.js
> +    },
Alterado

2021-04-23 17:20 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +    }
Sim, ele deveria ser `required`.

Slot criado.

2021-04-23 17:29 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +    },
corrigido

2021-04-23 18:14 UTC, caiotarifa commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +        </div>
Toda essa div (da linha `9` a `12` não é renderizada?

2021-04-23 20:14 UTC, leonardoMarco20 commented on ui/src/components/text-truncate/QasTextTruncate.vue
> +        </div>
adicionei o v-if apenas na linha 12, assim o ícone de fechar o dialog continua aparecendo.

2021-04-23 20:17 UTC, caiotarifa approved these changes

2021-04-26 18:31 UTC, merged