Feature/change qas profile
bildvitta/asteroid pull request #238
Opened 2021-04-26 21:13 UTC by leonardoMarco20

close #212

2021-04-27 01:24 UTC, caiotarifa requested changes

2021-04-27 01:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +    avatarSize,
Se é um método, deveria ter um verbo, ex: `getAvatarSize`

2021-04-27 01:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +              <qas-avatar :image="userAvatarImage" rounded :size="avatarSize()" :title="title" />
Se o método não tem parâmetro, pode-se ocultar os parênteses. `:size="avatarSize"`

2021-04-27 01:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +            <div>{{ subtitle }}</div>
Fico inconformado de não precisar de `v-if` para parâmetros não obrigatórios, rs.

2021-04-27 01:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +            <div class="inline-block">
Me parece ter muitas `div`s. Realmente precisamos de todas?

2021-04-27 01:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +      return this.$_untilMedium ? 'col' : 'row items-center'
Acho que podemos tirar o `info`, não parece ter feito sentido. E usamos `classes` ao invés de `class` nos nomes não? (Pq `class` é reservado)

2021-04-27 12:44 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +            <div class="inline-block">
removido uma `div` que estava a mais.

2021-04-27 12:44 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +      return this.$_untilMedium ? 'col' : 'row items-center'
corrigido

2021-04-27 12:54 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +            <div>{{ subtitle }}</div>
corrigido, e passado title para required

2021-04-27 13:07 UTC, leonardoMarco20 commented on ui/src/helpers/avatar-size.js
> +}
No Almobi essa function é repetida varias vezes quando usa a imagem do avatar.

2021-04-27 13:35 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +    avatarSize,
corrigido

2021-04-27 13:44 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +              <qas-avatar :image="userAvatarImage" rounded :size="avatarSize()" :title="title" />
Nesse caso eu precisei passar com os parênteses, se eu removo a função não é chamada.

2021-04-27 13:46 UTC, leonardoMarco20 commented on ui/src/helpers/status.js
> +  }
Corrigido.

2021-04-27 13:51 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.stories.js
> +      description: 'List of the fields to listed in grid.'
Corrigido. Lembrando que nossas guilda de inglês ocorrem todas às sextas às 18h. XD

2021-04-27 13:57 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.stories.js
> +        component: '.'
Por algum motivo voltei o texto que havia colocado. Corrigido.

2021-04-29 01:41 UTC, DouglasCalora requested changes

2021-04-29 01:41 UTC, DouglasCalora commented on ui/src/helpers/status.js
> +const setStatusLabel = (status, value) => {
Não acho que isto faz sentido estar aqui no asteroid, isto é muito especifico do almobi.

2021-04-29 13:57 UTC, leonardoMarco20 commented on ui/src/helpers/status.js
> +const setStatusLabel = (status, value) => {
Mas não seria interessante ter uma lista de status geral?

2021-04-30 04:13 UTC, caiotarifa requested changes

2021-04-30 04:13 UTC, caiotarifa commented on CHANGELOG.md
> +### Changed
Espaço para cima.

2021-04-30 04:13 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.vue
> +      require: true
Não seria `required`?

2021-04-30 04:13 UTC, caiotarifa commented on ui/src/helpers/status.js
> +const setStatusLabel = (status, value) => {
Pensando bem, é bem específico do Almobi mesmo... Coisas como `repassado` por exemplo, não faz sentido estar aqui.

2021-04-30 12:10 UTC, leonardoMarco20 commented on CHANGELOG.md
> +### Changed
corrigido

2021-04-30 12:10 UTC, leonardoMarco20 commented on ui/src/components/profile/QasProfile.vue
> +      require: true
corrigido

2021-04-30 12:25 UTC, leonardoMarco20 commented on ui/src/helpers/status.js
> +const setStatusLabel = (status, value) => {
Removido, no componente deixei um slot default para as informações principais.

2021-04-30 19:24 UTC, caiotarifa approved these changes

2021-04-30 19:24 UTC, caiotarifa commented on ui/src/components/profile/QasProfile.stories.js
> +    source: { code: `<qas-profile :fields="fields" :list="list" :result="result" :columns="${JSON.stringify(columns)}" />` }
`${JSON.stringify(columns)}` poderia estar na própria definição do `comuns`

```
const columns = JSON.stringify({
   name: { col: 12, sm: 6 },
   phone: { col: 12, sm: 6 },
   gender: { col: 12, sm: 6 },
   document: { col: 12, sm: 6 },
   address: { col: 6 },
   email: { col: 12, sm: 6 }
 })
```

Assim a gente economiza processamento na tela. (É irrelevante, por isso já vou aprovar e megear.)

2021-04-30 19:35 UTC, merged