mixins and others adjusts
bildvitta/asteroid pull request #242
Opened 2021-04-28 14:28 UTC by leonardoMarco20

close #236

2021-04-29 01:32 UTC, DouglasCalora requested changes
Muda o jeito que importamos antigamente ou é da mesma forma?

2021-04-29 01:32 UTC, DouglasCalora commented on ui/src/helpers/filters.js
> +  return value.map(itemValue => optionLabel(options, itemValue))
Porque esta alteração?

2021-04-29 13:53 UTC, leonardoMarco20 commented on ui/src/helpers/filters.js
> +  return value.map(itemValue => optionLabel(options, itemValue))
Foi pedido essa alteração, pois estava criando muitas quebras de linha.

2021-04-29 13:55 UTC, leonardoMarco20 commented
@DouglasCalora continua da mesma forma. Apenas foi adicionado os mixins no import.

2021-04-30 04:16 UTC, caiotarifa approved these changes

2021-04-30 19:49 UTC, merged