Feature/qas card
bildvitta/asteroid pull request #246
Opened 2021-04-30 18:25 UTC by leonardoMarco20

close #206

2021-05-11 14:43 UTC, DouglasCalora requested changes

2021-05-11 14:43 UTC, DouglasCalora commented on ui/src/components/card/QasCard.vue
> +    defaultImage: {
pq "default"? só `image` não resolveria?

2021-05-11 14:43 UTC, DouglasCalora commented on ui/src/components/card/QasCard.vue
> +    bgImagePositionClasses () {
Ela retorna somente uma classe, devei estar no singular.

2021-05-11 15:14 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    defaultImage: {
Pq seria a imagem default caso nao tiver imagem alguma. Esse seria o comportamento de um card que tem o espaço de header. 
![image](https://user-images.githubusercontent.com/50151901/117840240-5bac1a00-b252-11eb-83e8-9ebd8dd44635.png)

2021-05-11 16:21 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    bgImagePositionClasses () {
Por padrão mantemos como plural só que retornando um obj ou um array, faltou retornar lai um array. Corrigido.

2021-05-11 16:21 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    gutterClasses () {
Por padrão mantemos como plural só que retornando um obj ou um array, faltou retornar lai um array. Corrigido.

2021-05-11 16:28 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +      if (this.imagesLength) return this.fields.images.slice(0, 3)
Não precisou mais do primeiro if agora ele retorna uma imagem default se nao tiver uma lista de imagens.

2021-05-13 12:32 UTC, DouglasCalora approved these changes

2021-05-13 12:33 UTC, merged

2021-05-13 14:39 UTC, caiotarifa requested changes

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +    }
Por que pegamos esse `data.image` é responsabilidade do componente fazer esse tipo de tratativa?

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +    },
Não usar `formMode` para estilos (vide "TODO" que deixei no QasBox) pois não representa o formato que o componente terá.

Ao invés disso, prefira algo mais semântico e que corresponda ao resultado, como `outlined`.

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +      </div>
Aqui, como não tem nada dentro do _slot_, não precisa do `useActions`.

Basta transformar `useActions` em uma computada que verifica se o slot veio vazio.

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/settings-menu/QasSettingsMenu.vue
> +    position:absolute;
Espaço entre o `:` e o texto.

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +    },
Qual o propósito disso?

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +    },
As imagens vem no `fields`, é isso?

• E se estiverem em `fields.customImages` e não em `fields.images`?
• E se eu quiser usar esse componente "manualmente"?

Minha proposta é criar uma prop `image` que recebe um array, ou seja, uma lista das imagens que precisam ser exibidas. Tratar `fields` ou respostas equivocadas de API tornam esse componente menos reutilizável.

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +            <q-carousel-slide v-for="(item, index) in images" :key="index" class="bg-no-repeat" :class="bgImagePositionClasses" :img-src="getImage(item)" :name="index" />
Por que usamos `background` para exibir as imagens?

2021-05-13 14:39 UTC, caiotarifa commented on ui/src/components/card/QasCard.vue
> +    defaultImage: {
Vide o comentário que deixei em `fields`, não vejo necessidade dessa prop. Acho que poderia vir em `images`.

2021-05-13 19:42 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    }
Sim, porque o default é ter um carousel no header. Seguindo o layout a maioria dos cards teriam uma imagem.

2021-05-13 19:57 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +            <q-carousel-slide v-for="(item, index) in images" :key="index" class="bg-no-repeat" :class="bgImagePositionClasses" :img-src="getImage(item)" :name="index" />
Pra poder usar o cover, algumas imagens estavam vindo pequenas.

2021-05-14 13:18 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +}
Classe criada.

2021-05-14 13:23 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    },
Alterado.

2021-05-14 13:24 UTC, leonardoMarco20 commented on ui/src/components/settings-menu/QasSettingsMenu.vue
> +    position:absolute;
Corrigido

2021-05-14 13:25 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    },
Por algum motivo essa computada retornou, já removi ela.

2021-05-14 13:43 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    },
Realmente essa prop `fields` não fazia sentido, removida e agora esta sendo tratada como `images`.

2021-05-14 13:56 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +    }
Removi esse method, agora com a prop image sendo um array, não precisou mais dela.

2021-05-14 15:02 UTC, leonardoMarco20 commented on ui/src/components/card/QasCard.vue
> +      </div>
Desconhecia essa form de uso criei dessa forma:

```
useActions () {
  return !!(this.$slots.actions || this.$scopedSlots.actions)
}
```