TabsGenerator Documentation
bildvitta/asteroid pull request #3
Opened 2020-12-17 17:47 UTC by RafaelM-DEv

2021-01-11 20:53 UTC, caiotarifa commented
Ajustar conflito.

2021-01-11 20:56 UTC, caiotarifa requested changes

2021-01-11 20:56 UTC, caiotarifa commented on ui/index.js
> +  QBadge,
Ordem alfabética.

2021-01-11 20:56 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +                          This component implements QTabs e QTAb https://quasar.dev/vue-components/tabs#Introduction`
Coloque como link (vide QasBtn).

2021-01-11 20:56 UTC, caiotarifa commented on ui/src/index.js
> +  TabsGenerator,
Ordem alfabética.

2021-01-11 20:56 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +`
Pq saiu definindo um monte de variáveis? Faz no próprio objeto.

2021-01-11 20:56 UTC, caiotarifa commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +const divTextIntoTab = '\'I\'m inside the tab!\''
Por que isso está envolto em aspas?

2021-01-12 17:15 UTC, RafaelM-DEv commented on ui/index.js
> +  QBadge,
feito

2021-01-12 17:30 UTC, RafaelM-DEv commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +                          This component implements QTabs e QTAb https://quasar.dev/vue-components/tabs#Introduction`
feito

2021-01-12 17:37 UTC, RafaelM-DEv commented on ui/src/index.js
> +  TabsGenerator,
feito

2021-01-12 17:39 UTC, RafaelM-DEv commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +`
feito

2021-01-12 17:40 UTC, RafaelM-DEv commented on ui/src/components/tabs-generator/QasTabsGenerator.stories.js
> +const divTextIntoTab = '\'I\'m inside the tab!\''
era só um estilo que tinha no exemplo

2021-01-23 23:05 UTC, merged