Adjusting 404 page
bildvitta/asteroid pull request #335
Opened 2021-06-11 18:17 UTC by plowzzer

Adjusting the 'Voltar' link on 404 page

Ajustando o link 'Voltar' na página 404

2021-06-11 18:18 UTC, plowzzer commented
Você pode estar se perguntando o porque que eu coloquei um splice com 2 índices depois do lenght e removendo 2 links de lá, pelo simples fato dele bater a página, não encontrar resultados e ir para a página do 404, nesse caso eu estou removendo tanto a 404 quanto a pagina que deu erro e voltando para a anterior dele...

2021-06-21 11:44 UTC, caiotarifa requested changes

2021-06-21 12:00 UTC, plowzzer commented on ui/src/pages/NotFound.vue
> +        const redirect = history.list.pop()
Tanto pelo botão nativo do navegador quanto o botão de voltar estão com o mesmo comportamento após a função

2021-06-21 12:32 UTC, DouglasCalora requested changes

2021-06-21 12:32 UTC, DouglasCalora commented on ui/src/pages/NotFound.vue
> +      history.list.splice(history.list.length-2,2)
`history.list.splice(history.list.length - 2, 2)`

2021-06-21 18:21 UTC, DouglasCalora approved these changes

2021-06-22 14:56 UTC, plowzzer commented on ui/src/pages/NotFound.vue
> +      history.list.splice(history.list.length -2, 2)
Eu não consigo explicar o porque que o back do navegador funciona nesse caso, porque a função de `history.list.splice(history.list.length -2, 2)` remove os últimos 2 links do history, sendo no caso, o de entrada da pagina que gerou o erro e a página do 404 implementada aqui.

Por algum motivo que eu ainda não entendi, o back do navegador volta 1 pagina, porem ignora a 404 ou a anterior a ela (o que gerou o erro).

eu acho que o `history.back()` deveria voltar 1 pagina, e esse comportamento em especial volta 2.

2021-06-22 20:35 UTC, caiotarifa commented on ui/src/pages/NotFound.vue
> +      history.list.splice(history.list.length -2, 2)
O `history.back()` faz exatamente a mesma coisa que clicar no botão voltar do navegador. Por que não usamos ele então?

2021-06-22 21:22 UTC, plowzzer commented on ui/src/pages/NotFound.vue
> +      history.list.splice(history.list.length -2, 2)
com history,back() `TypeError: can't access property "back", _vm.history is undefined`

O history que estamos usando é o history do `historyHandler` do helpers... esse history que você esta falando? é um pacote do quasar?

2021-06-28 21:45 UTC, caiotarifa commented on ui/src/pages/NotFound.vue
> +      history.list.splice(history.list.length -2, 2)
Não, do `window` mesmo.

```js
window.history.back()
```

Isso aí faz a mesma coisa que o botão voltar do navegador.

2023-04-14 19:20 UTC, closed without merging