Feature/signature pad
bildvitta/asteroid pull request #336
Opened 2021-06-11 18:20 UTC by eliasassuncao

2021-06-11 20:08 UTC, DouglasCalora requested changes

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    height: {
se eu querer height `50vh` vou conseguir?

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    newSignaturePad () {
setSignaturePad

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    signatureIsEmpty () {
me parece que retorna um boolean elo nome, mas é uma ação de emit, talvez algo mais generico `emitter` `isEmptyEmitter`

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    setWidthCanvas () {
setCanvasWidth

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +  }
Normalmente não damos esse primeiro espaço na indentação no style

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +      right: 0;
Já não tem classes do quasar para fazer isto?

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-uploader/QasSignatureUploader.stories.js
> +    input: hides
pq esta escondendo?

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    labelUpload: {
uploadLabel

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    labelSignature: {
SignatureLabel

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
>    <q-field borderless :error="error" :error-message="errorMessage" :hint="hintValue">
Pq precisou fazer alterações neste componente?

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/helpers/base64-to-blob.js
> +  for(let position = 0; position < imageContent.length; position++) {
espaço no for

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/helpers/base64-to-blob.js
> +  return blob;
remover `;`

2021-06-11 20:08 UTC, DouglasCalora commented on ui/src/helpers/base64-to-blob.js
> +export default function (base64) {
Precisamos padronizar isto no asteroid, mas mantem por hora o nome do arquivo em capslock, base64ToBlob.js

2021-06-11 20:18 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +      console.log(newValue, '<----- new value')
feito.

2021-06-11 20:20 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    height: {
é uma string repassada para o canvas, se o canvas tiver suporte para isso, sim.

2021-06-11 20:21 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    newSignaturePad () {
mas eu estou estanciando um novo, faz sentido chamar de set?

2021-06-11 20:22 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    signatureIsEmpty () {
feito.

2021-06-11 20:23 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    setWidthCanvas () {
feito.

2021-06-11 20:45 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +  }
feito.

2021-06-11 20:48 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +      right: 0;
desconheço, manja alguma classe?

2021-06-11 20:51 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.stories.js
> +    input: hides
é um evento padrão por existir v-model, acha válido explicar?

2021-06-11 21:23 UTC, eliasassuncao commented on ui/src/helpers/base64-to-blob.js
> +export default function (base64) {
feito.

2021-06-11 21:23 UTC, eliasassuncao commented on ui/src/helpers/base64-to-blob.js
> +  return blob;
feito.

2021-06-11 21:23 UTC, eliasassuncao commented on ui/src/helpers/base64-to-blob.js
> +  for(let position = 0; position < imageContent.length; position++) {
feito.

2021-06-11 21:24 UTC, eliasassuncao commented on ui/src/components/uploader/QasUploader.vue
>    <q-field borderless :error="error" :error-message="errorMessage" :hint="hintValue">
alinhado via discord.

2021-06-11 21:25 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    labelSignature: {
feito.

2021-06-11 21:26 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    labelUpload: {
feito.

2021-06-11 21:27 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    newSignaturePad () {
trocado para `setupSignaturePad`

2021-06-11 21:30 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.stories.js
> +      description: 'Options you can pass to customize your component. (https://github.com/szimek/signature_pad#options)',
feito.

2021-06-11 21:32 UTC, eliasassuncao commented on ui/src/components/avatar/QasAvatar.vue
> +
foi pra remover o `background-color` caso seja imagem, q é o que tava causando com q as imagens brancas aparentavam aquelas bordinhas.
![image](https://user-images.githubusercontent.com/29342573/121750752-5a853b80-cae3-11eb-9335-dd8decb53883.png)

2021-06-11 21:32 UTC, eliasassuncao commented on ui/src/components/avatar/QasAvatar.vue
> +
foi adicionado no changelog.

2021-06-11 21:39 UTC, eliasassuncao commented on ui/src/components/signature-pad/QasSignaturePad.stories.js
> +    isEmpty: {
o correto é usar o evento `:is-empty.sync="isEmpty"`, então escondi essa props. Acha interessante colocar a msm explicação? não pode parecer q são props diferentes.

2021-06-14 17:27 UTC, DouglasCalora approved these changes

2021-06-14 17:27 UTC, merged

2021-06-21 13:59 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +        const file = new File([blob], `${fileName}.png`, { type: 'image/png' })
No caso do componente q faz o upload, a gente quer q sempre seja uma imagem. No caso do componente que é somente a assinatura, caso queiramos criar outros componentes q salve em outro tipo, damos a liberdade de passar o type. Faz sentido?

2021-06-21 19:47 UTC, eliasassuncao commented on ui/src/helpers/base64ToBlob.js
> +  for (let position = 0; position < imageContent.length; position++) {
feito.

2021-06-21 19:47 UTC, eliasassuncao commented on ui/src/helpers/base64ToBlob.js
> +  return blob
feito.

2021-06-21 20:47 UTC, caiotarifa commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +        const file = new File([blob], `${fileName}.png`, { type: 'image/png' })
Não muito, pois se os outros componentes utilizarem o mesmo `uploader` eles não poderão salvar em outros tipos (ex: SVG).