AppBar Component changes
bildvitta/asteroid pull request #341
Opened 2021-06-16 18:54 UTC by plowzzer

- Modifficação na estrutura do notifications (caso não tenha suporte para notificação não mostrar)
- Modificação nos espaçamentos do appsBar com o icone de notifications

2021-06-16 20:24 UTC, DouglasCalora requested changes

2021-06-16 20:24 UTC, DouglasCalora commented on ui/src/components/app-bar/QasAppBar.vue
> +    <div v-if="notifications">
dessa forma notifications sempre vai existir, pq `!!({}) === true` tu precisa validar o length `Object.keys(notifications).length`

2021-06-16 20:24 UTC, DouglasCalora commented on ui/src/components/app-bar/QasAppBar.vue
> +        <q-badge v-if="notifications" color="red" floating>{{notifications.count}}</q-badge>
faltando espaço nas chaves

2021-06-16 20:24 UTC, DouglasCalora commented on ui/src/components/app-bar/QasAppBar.vue
> +      type: () => ({}),
não é type, é `default`

2021-06-16 20:24 UTC, DouglasCalora commented on ui/src/components/apps-menu/QasAppsMenu.vue
> +  <q-btn class="q-mr-md" v-bind="$attrs" dense icon="o_apps" round unelevated>
não precisa ter espaço nos 2 lados?

2021-06-16 20:26 UTC, plowzzer commented on ui/src/components/apps-menu/QasAppsMenu.vue
> +  <q-btn class="q-mr-md" v-bind="$attrs" dense icon="o_apps" round unelevated>
coloquei sempre a esquerda... se não existir um... vai dar ruim... ou o espaço vai ficar mto grande

Nesse caso ai... tivemos um espaço pros 2 lados no app e não tinha no notifications... ai ele ficou em cima

2021-06-21 11:44 UTC, caiotarifa requested changes

2021-06-21 12:08 UTC, plowzzer commented on ui/src/components/app-bar/QasAppBar.vue
> +    haveNotifications () {
Apesar de ser mais sonoro...  o “Has” é usado para os pronomes pessoais na terceira pessoa: He, She e It, e “have” para os outros pronomes: I, You, We, They.

Estou levando em consideração um "You have notifications" do que um "It (He or She) has notifications"

2021-06-21 12:10 UTC, plowzzer commented on ui/src/components/app-bar/QasAppBar.vue
> +        <q-badge v-if="notifications" color="red" floating>{{ notifications.count }}</q-badge>
Ainda não sabemos como o notificações vai funcionar, porem o que foi feito no momento é tem como objetivo esconder a notificação do topo. Ainda mantendo o TODO do que mais implementar para essa func.

2021-06-21 12:10 UTC, plowzzer commented on ui/src/components/apps-menu/QasAppsMenu.vue
> +  <q-btn class="q-mr-md" v-bind="$attrs" dense icon="o_apps" round unelevated>
Concordo.

2021-06-21 12:34 UTC, DouglasCalora commented on ui/src/components/app-bar/QasAppBar.vue
> +    haveNotifications () {
Mas acho que isto cai no `it` e seria `has`, `user has notifications`

2021-06-21 18:19 UTC, DouglasCalora approved these changes

2021-06-21 18:32 UTC, caiotarifa commented on ui/src/components/app-bar/QasAppBar.vue
> +    haveNotifications () {
Entendo, mas como não temos o `You` ou `I`, acho melhor usarmos `has` já que não usamos `have` em nenhum outro local.

2021-06-21 18:33 UTC, caiotarifa commented on ui/src/components/app-bar/QasAppBar.vue
> +        <q-badge v-if="notifications" color="red" floating>{{ notifications.count }}</q-badge>
Entendi... mais para frente teremos que mudar de acordo com o que for definido, é isso?

2021-06-21 20:49 UTC, caiotarifa approved these changes

2021-06-22 14:43 UTC, plowzzer commented on ui/src/components/app-bar/QasAppBar.vue
> +        <q-badge v-if="notifications" color="red" floating>{{ notifications.count }}</q-badge>
Sim

2021-06-22 17:36 UTC, merged