nested fields changes
bildvitta/asteroid pull request #354
Opened 2021-06-24 14:22 UTC by leonardoMarco20

close #344

2021-07-02 17:04 UTC, DouglasCalora requested changes
Não entendi o porque daquele slot default, mas se realmente for prosseguir com ele, esta faltando adc na doc do storybook.

2021-07-02 17:04 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +                <slot>
por que do slot?

2021-07-02 17:04 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      return this.emitter(null, this.nested.length - 1)
pq precisa fazer este null? nos emitter?

2021-07-02 17:04 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
>      }
E se eu não quiser usar o index?

2021-07-02 17:04 UTC, DouglasCalora commented on CHANGELOG.md
> +- Nested-field returning changed line index
```md
- `QasNestedFields` returning changed line index
- `QasNestedFields`
```

2021-07-02 17:04 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    setRowLabel (rowKey) {
É rowKey ou rowIndex?

2021-07-02 17:06 UTC, DouglasCalora requested changes

2021-07-02 17:06 UTC, DouglasCalora commented on CHANGELOG.md
> +
```md
- `QasNestedFields` returning changed line index.
- `QasNestedFields` enumerating label.
```

2021-07-06 20:26 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +                <slot>
No almobi caímos em um problema, onde precisamos tratar o disabled de um field específico, conversando com o Caio, ele disse que precisaria criar esse slot, só que não dei continuidade nessa solução.

2021-07-06 20:34 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    setRowLabel (rowKey) {
No caso estou querendo o index da row, então acho que seria melhor rowIndex

2021-07-06 20:36 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
>      }
Em muitos casos no almobi preciso do index da row para fazer alguns tratamentos, faria sentido ter uma prop para dizer se quero ou nao retornar o index?

2021-07-06 20:40 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      return this.emitter(null, this.nested.length - 1)
Fazendo junto com o Gui, lembro dele ter falado para colocar null pois pode não ter um value e ficar undefined.

2021-07-07 13:29 UTC, leonardoMarco20 commented on CHANGELOG.md
> +
corrigido

2021-07-15 20:05 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
>      }
Eu acho que faz, deixa ela com `default: true`

2021-07-16 14:06 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
>      }
prop criada

2021-07-19 17:19 UTC, plowzzer approved these changes

2021-07-20 16:16 UTC, DouglasCalora requested changes

2021-07-20 16:16 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +        <div v-for="(row, index) in nested" :id="`row${index}`" :key="index" class="full-width">
aqui seria bom adc `-` `row-${index}`

2021-07-20 16:16 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    name () {
`fieldName` não deixaria mais claro que é o nome do field?

2021-07-20 16:19 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +        <div v-for="(row, index) in nested" :id="`row${index}`" :key="index" class="full-width">
Outra coisa, não corre o risco de ter id duplicado?

2021-07-20 16:34 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +        <div v-for="(row, index) in nested" :id="`row${index}`" :key="index" class="full-width">
corrigido

2021-07-20 16:34 UTC, leonardoMarco20 commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    name () {
corrigido

2021-07-20 16:40 UTC, DouglasCalora approved these changes

2021-07-20 16:40 UTC, merged