Feature/add money mask
bildvitta/asteroid pull request #363
Opened 2021-07-07 21:05 UTC by leonardoMarco20

2021-07-07 21:27 UTC, AntaresT approved these changes

2021-07-07 21:31 UTC, eliasassuncao requested changes

2021-07-07 21:31 UTC, eliasassuncao commented on ui/src/helpers/filters.js
> +    squareArea: () => squareArea(value)
seguir o padrão kebab-case, `square-area`

2021-07-07 21:32 UTC, eliasassuncao requested changes

2021-07-07 21:32 UTC, eliasassuncao commented on ui/src/helpers/filters.js
> +  return value ? value.toLocaleString('pt-BR') : ''
o valor é númerico, e caso não tenha value, vc retorna uma string vazia, isso poderia causar algum problema?
não seria melhor
`return value ? value.toLocaleString('pt-BR') : value`

2021-07-07 21:32 UTC, eliasassuncao commented on ui/src/helpers/filters.js
> +  return value ? `${decimal(value)} ${suffix}` : ''
o valor é númerico, e caso não tenha value, vc retorna uma string vazia, isso poderia causar algum problema?
não seria melhor
`return value ? ${decimal(value)} ${suffix} : value `

2021-07-07 23:28 UTC, plowzzer commented on ui/src/helpers/filters.js
> +  return value ? value.toLocaleString('pt-BR') : ''
Caso não venha nenhum valor, retornar vazio mesmo... é assim que estão as outras masks

2021-07-07 23:29 UTC, plowzzer commented on ui/src/helpers/filters.js
> +    squareArea: () => squareArea(value)
Concordo @leonardoMarco20, na correria eu acho que ignoramos isso dai :)

2021-07-07 23:30 UTC, plowzzer requested changes
Acho que apenas a mudança no square-area... na minha visão

2021-07-08 20:24 UTC, eliasassuncao commented on ui/src/helpers/filters.js
> +  return value ? value.toLocaleString('pt-BR') : ''
mas é uma mask pra número, se um campo type number tiver valor de string ele não vai falar q espera um tipo númerico?

2021-07-12 13:06 UTC, plowzzer commented on ui/src/helpers/filters.js
> +  return value ? value.toLocaleString('pt-BR') : ''
![image](https://user-images.githubusercontent.com/444696/125292340-c03e3080-e2f8-11eb-8f8a-c3aae232715b.png)

Isso que vai acontecer @eliasassuncao

2021-07-12 13:14 UTC, plowzzer commented on ui/src/helpers/filters.js
> +  return value ? `${decimal(value)} ${suffix}` : ''
Acho que precisamos entender melhor o que vamos apresentar com essa mask: 
o return como o elias esta propondo: 
![image](https://user-images.githubusercontent.com/444696/125293514-df898d80-e2f9-11eb-8e09-169a33eaf36e.png)

como esta agora:
![image](https://user-images.githubusercontent.com/444696/125293588-ef08d680-e2f9-11eb-914c-891684b49aa6.png)
igual

como eu acho que deveria ser:
![image](https://user-images.githubusercontent.com/444696/125293660-0051e300-e2fa-11eb-849d-0c9e79ebddc2.png)

2021-07-12 16:37 UTC, caiotarifa commented on ui/src/helpers/filters.js
> +    squareArea: () => squareArea(value)
👍

2021-07-12 16:38 UTC, caiotarifa commented on ui/src/helpers/filters.js
> +  return value ? value.toLocaleString('pt-BR') : ''
Vai sempre retornar _string_, @eliasassuncao. Campos com _type_ `number` não pode receber máscara.

2021-07-12 16:40 UTC, caiotarifa commented on ui/src/helpers/filters.js
> +  return value ? `${decimal(value)} ${suffix}` : ''
Ou pode já processar o decimal direto no `value` para evitar reprocessamento:

```js
value = decimal(value)
```

2021-07-13 14:41 UTC, leonardoMarco20 commented on ui/src/helpers/filters.js
> +    squareArea: () => squareArea(value)
corrigido

2021-07-13 16:35 UTC, leonardoMarco20 commented on ui/src/helpers/filters.js
> +  return value ? `${decimal(value)} ${suffix}` : ''
Atualizado.

2021-07-13 16:53 UTC, plowzzer approved these changes

2021-07-16 17:05 UTC, eliasassuncao approved these changes

2021-07-16 17:42 UTC, merged