slots in autocomplete component
bildvitta/asteroid pull request #391
Opened 2021-08-31 19:07 UTC by eliasassuncao

2021-08-31 19:30 UTC, gqueiroz1 requested changes

2021-08-31 19:30 UTC, gqueiroz1 commented on ui/src/components/auto-complete/QasAutoComplete.vue
>      multiple () {
`isMultiple` que tal ?

2021-08-31 19:45 UTC, eliasassuncao commented on ui/src/components/auto-complete/QasAutoComplete.vue
>      multiple () {
feito

2021-08-31 19:46 UTC, gqueiroz1 approved these changes

2021-09-01 18:25 UTC, DouglasCalora requested changes
Poderia alterar essa descrição 
![image](https://user-images.githubusercontent.com/32134017/131723373-c247f551-bddd-4e56-841c-757c7caa746d.png)

Outra coisa, conseguimos fazer um dynamic import para nem importar o fuse caso não use?

2021-09-01 18:25 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.stories.js
> +      description: 'Text for when there are no results for the search.'
`Text for empty results`

2021-09-01 18:25 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.vue
> +      this.selectModel = this.value
Não precisa fazer o tratamento do multiple?

2021-09-01 18:25 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.vue
> +  <q-select v-model="selectModel" v-bind="$attrs" clearable emit-value map-options :options="filteredOptions" outlined :use-input="searchable" v-on="$listeners" @filter="filterOptions">
clearable emit-value map-options, dessa forma  conseguiremos sobreescrever caso precise? se não, precisa adc como prop default, n?

2021-09-01 18:25 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.vue
>      filterOptions (value, update) {
Não precisa fazer um if para verificar se tem a prop searchable? tipo se não tiver nem chama a fn update, algo assim

2021-09-01 19:28 UTC, gqueiroz1 requested changes

2021-09-01 19:28 UTC, gqueiroz1 commented on ui/src/components/form-view/QasFormView.vue
>              <qas-btn v-close-popup="dialog" class="full-width" :data-cy="`btnCancel-${entity}`" :disable="disable || isSubmiting" :label="cancelButton" outline type="button" @click="cancel" />
lógica na view

2021-09-01 19:28 UTC, gqueiroz1 commented on ui/src/components/form-view/QasFormView.vue
>              <qas-btn v-close-popup="dialog" class="full-width" :data-cy="`btnCancel-${entity}`" :disable="disable || isSubmiting" :label="cancelButton" outline type="button" @click="cancel" />
```
disableCancelButton () {
  return this.disable || this.isSubmitting
}
```

tbm tem um mistype em `submitting`

2021-09-01 19:28 UTC, gqueiroz1 commented on ui/src/components/form-view/QasFormView.vue
> +            <qas-btn class="full-width" :data-cy="`btnSave-${entity}`" :disable="disable" :label="submitButton" :loading="isSubmiting" type="submit" />
seria bom criar uma computada pra esse button tbm, pra manter o padrão do botão de cancelar

2021-09-01 19:29 UTC, plowzzer approved these changes

2021-09-01 19:32 UTC, eliasassuncao commented on ui/src/components/auto-complete/QasAutoComplete.stories.js
> +      description: 'Text for when there are no results for the search.'
feito

2021-09-01 19:32 UTC, eliasassuncao commented on ui/src/components/auto-complete/QasAutoComplete.vue
> +    noOptionText: {
já está, porém esse é o arquivo antigo, não sei pq está q existe ainda '-'

2021-09-01 19:33 UTC, eliasassuncao commented on ui/src/components/select/QasSelect.stories.js
> +      description: 'Text for when there are no results for the search.'
feito

2021-09-01 19:42 UTC, eliasassuncao commented on ui/src/components/select/QasSelect.vue
>      filterOptions (value, update) {
se não passar pelo`update`, o componente fica com loading nos options. O que fiz é colocar um return logo no começo se não conter a prop

2021-09-01 19:43 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
>              <qas-btn v-close-popup="dialog" class="full-width" :data-cy="`btnCancel-${entity}`" :disable="disable || isSubmiting" :label="cancelButton" outline type="button" @click="cancel" />
feito

2021-09-01 19:47 UTC, gqueiroz1 approved these changes

2021-09-01 20:17 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
>              <qas-btn v-close-popup="dialog" class="full-width" :data-cy="`btnCancel-${entity}`" :disable="disable || isSubmiting" :label="cancelButton" outline type="button" @click="cancel" />
alinhado discord q faz mais sentido repassar a props do q criar a computada

2021-09-01 20:56 UTC, DouglasCalora approved these changes

2021-09-01 20:57 UTC, merged