Uploader Documentation
bildvitta/asteroid pull request #4
Opened 2021-01-06 18:42 UTC by RafaelM-DEv

2021-01-11 20:12 UTC, caiotarifa requested changes

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/components/uploader/QasUploader.vue
> +        throw error
É só retirar o `catch`. Em hipótese alguma desabilite alguma função do ESLint.

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/index.js
> +    Vue.component('qas-uploader', Uploader)
Precisa ajustar.

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/index.js
> +import Uploader from './components/uploader/QasUploader'
Use ordem alfabética.

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/components/uploader/QasUploader.stories.js
> +      description: 'hint message'
Não pode melhorar essa descrição?

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/components/uploader/QasUploader.stories.js
> +      description: 'Vuex entity. more info: https://vuex.vuejs.org/',
Esse link não vai trazer mais informações para isso. @DouglasCalora consegue explicar como as entidades funcionam?

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/components/uploader/QasUploader.stories.js
> +      }
O que isso faz? É necessário?

2021-01-11 20:12 UTC, caiotarifa commented on ui/src/components/uploader/QasUploader.stories.js
> +    }
Não era para estar desabilitado, lembra?

2021-01-11 20:12 UTC, caiotarifa commented on ui/index.js
> +  QList,
Ordem alfabética.

2021-01-11 20:54 UTC, RafaelM-DEv commented on ui/src/components/uploader/QasUploader.vue
> +        throw error
entendido

2021-01-11 21:08 UTC, RafaelM-DEv commented on ui/src/components/uploader/QasUploader.stories.js
> +      }
sim, eu coloquei a definição do Default na tabela da Doc como `' '` aspas simples, sem isso ele fica com um `-` traço sem definição.

2021-01-11 21:28 UTC, RafaelM-DEv commented on ui/src/components/uploader/QasUploader.stories.js
> +    }
sim, fiz as definições

2021-01-12 12:58 UTC, RafaelM-DEv commented on ui/src/index.js
> +    Vue.component('qas-uploader', Uploader)
Feito

2021-01-12 12:59 UTC, RafaelM-DEv commented on ui/src/index.js
> +import Uploader from './components/uploader/QasUploader'
ok

2021-01-12 13:37 UTC, RafaelM-DEv commented on ui/src/components/uploader/QasUploader.stories.js
> +      description: 'hint message'
opa, feito

2021-01-12 13:56 UTC, RafaelM-DEv commented on ui/src/components/uploader/QasUploader.stories.js
> +      description: 'Vuex entity. more info: https://vuex.vuejs.org/',
pedi ao Haynes me explicar como funciona o `S3` e as entidades, e o que peguei foi que a entidade é usada pelo back-end para saber o tipo do arquivo que 
está sendo enviado para o bucket, o back-end configura qual será essas entidades.

pode ser essa descrição?

2021-01-12 13:57 UTC, RafaelM-DEv commented on ui/index.js
> +  QList,
feito

2021-01-22 01:06 UTC, merged