Ajustes no nested fields
bildvitta/asteroid pull request #400
Opened 2021-09-16 18:18 UTC by plowzzer

### Problema:
Atualmente, ao colocar um template de nested fields, gera um erro quando o code tentasetar o focus, por conta da referencia do form `ref="formGenerator"` não existir fora do componente

### Solução:
Passamos a referencia para a `div` pai, e trocamos a funcionalidade do setFocus para pegar o primeiro input, select ou textarea com o `querySelector`

### Commits: 
- setFocus adjustments

2021-09-16 18:32 UTC, caiotarifa approved these changes

2021-09-16 19:33 UTC, DouglasCalora requested changes
```
- Isto quebra de alguma forma os componentes que já utilizam?
- Passou no storybook para ver se tem algum erro de lint?
```

2021-09-20 12:47 UTC, plowzzer commented
> 
> 
> ```
> - Isto quebra de alguma forma os componentes que já utilizam?
> - Passou no storybook para ver se tem algum erro de lint?
> - Não deveria estar no changelog?
> ```

- Sobre a utilização em outros lugares, ele esta funcionando porem dando aquele warning do vuex ao utilizar com template dentro do nested fields (no caso para o form-generator ou field)
- Já o storybook não builda aqui de jeito nenhum... talvez eu precise fazer alguma coisa aqui para ajustar, ele estoura tanto erro que não consigo nem "trackear" o que pode ser

2021-09-21 13:37 UTC, DouglasCalora approved these changes

2021-09-21 13:55 UTC, merged