Fix/tabs and input adjusts
bildvitta/asteroid pull request #406
Opened 2021-09-28 19:42 UTC by leonardoMarco20

Correção em `qas-tabs` -  Alteração do nome do slot `tab-slot` para `tab-after` e nome dos slots usando `tab.value`.
Correção em `qas-input` - Correção na mask de CPF.

2021-09-28 19:47 UTC, caiotarifa requested changes
Foi alinhado com todos os projetos essas mudanças de nome? Pois quebram coisas.

2021-09-28 19:47 UTC, caiotarifa commented on ui/src/components/input/QasInput.vue
> +        document: () => this.toggleMask('###.###.###-##', '##.###.###/####-##'),
Isso foi testado? Lembro que precisava de um a mais justamente para fazer a transição para a outra máscara (igual telefone).

2021-09-28 20:22 UTC, leonardoMarco20 commented on ui/src/components/input/QasInput.vue
> +        document: () => this.toggleMask('###.###.###-##', '##.###.###/####-##'),
Desfiz as alterações de máscara.

2021-09-29 17:00 UTC, caiotarifa approved these changes

2021-09-29 18:22 UTC, plowzzer approved these changes

2021-10-06 17:14 UTC, merged