QasNumericInput
bildvitta/asteroid pull request #424
Opened 2021-10-18 20:34 UTC by caiotarifa

Essa requisição tem por objetivo substituir o atual `QasDecimalInput` pelo `QasNumericInput`. A mudança de nome está sendo proposta para que seja mais semântica e aderente ao que o componente se propõe a fazer.

Ainda existem algumas pendências para que o componente possa ser lançado.

- [ ] Propriedades para configurar o campo para ser `integer`, `decimal` e `money`.
- [ ] Tipo `integer` por padrão.
- [ ] Configurar o `money` por moeda (`brazilian` por padrão).
- [ ] Propriedade para permitir valores negativos (`true` por padrão).
- [ ] Propriedade para permitir valores positivos (`true` por padrão).
- [ ] [Propriedade v-bind para repassar as configurações para o AutoNumeric.js.](http://autonumeric.org/guide)
- [ ] Analisar o impacto da mudança em todos os projetos que o utilizam.

2021-10-19 13:41 UTC, eliasassuncao requested changes

2021-10-19 13:41 UTC, eliasassuncao commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      <input v-show="floatingLabel" ref="input" class="q-field__input" :id="id" :model-value="value" @input="event => emitValue(event.target.value)">
não seria melhor criar um método pro `@input` ?

2021-10-19 13:41 UTC, eliasassuncao commented on ui/src/components/numeric-input/QasNumericInput.vue
> +        return typeof value === 'number' || typeof value === 'string' || value === '' || value === null
seria melhor criar um array dos tipos aceitos, ou então ` return typeof value !== undefined`

```
  const acceptedTypes = ['number', 'string', null, '']
  
  return acceptedTypes.includes(typeof value)

```

2021-10-19 16:51 UTC, DouglasCalora requested changes

2021-10-19 17:00 UTC, caiotarifa commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      <input v-show="floatingLabel" ref="input" class="q-field__input" :id="id" :model-value="value" @input="event => emitValue(event.target.value)">
É que no caso a `emitValue` vem no escopo do `template`.

2022-01-05 23:54 UTC, DouglasCalora requested changes

2022-01-05 23:54 UTC, DouglasCalora commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      }
Não entendi, esta recuperando o value para reatribuir? Não seria só repassar `this.autoNumeric.getNumber()` direto para o emit?
 
```suggestion
      set () {
        this.$emit('input', this.autoNumeric.getNumber())
      }
```

2022-01-05 23:54 UTC, DouglasCalora commented on ui/src/components/numeric-input/QasNumericInput.vue
> +    const AutoNumericPredefinedOptions = AutoNumeric.getPredefinedOptions()
Neste caso acho que seria `camelCase`
```suggestion
    const autoNumericPredefinedOptions = AutoNumeric.getPredefinedOptions()
```

2022-01-05 23:54 UTC, DouglasCalora commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      }
Assim já não resolveria? `option = Array.isArray(option) ? option : [option]`

2022-01-05 23:54 UTC, DouglasCalora commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      }
Ai não precisaria de ter um if no meio do codigo

2022-01-05 23:54 UTC, DouglasCalora commented on ui/src/components/numeric-input/QasNumericInput.vue
> +    function getPredefinedOptions (option) {
Sempre que precisamos usar metodo dentro do created declaramos em methods e não uma fn dentro do created

2022-01-06 00:15 UTC, caiotarifa commented on ui/src/components/numeric-input/QasNumericInput.vue
> +      }
Pode ser mais curto, porém menos performático.

O motivo é que obrigar a atribuição de uma variável tem custo (acessar o endereço de memória e substituir o conteúdo no espaço). Na minha solução original, a condição testa a necessidade e só atribuição caso precise.

2022-01-06 00:43 UTC, caiotarifa commented on ui/src/components/numeric-input/QasNumericInput.vue
> +    function getPredefinedOptions (option) {
Vou remover a função, não há necessidade.

2022-01-06 20:56 UTC, eliasassuncao requested changes

2022-01-06 20:56 UTC, eliasassuncao commented on ui/src/components/numeric-input/QasNumericInput.vue
> +        <input v-show="floatingLabel" ref="input" class="q-field__input" :id="id" :model-value="value" @input="emitValue($event.target.value)">
qual o motivo de não usar `v-if` ?

2022-01-06 21:06 UTC, eliasassuncao approved these changes

2022-01-07 13:27 UTC, merged