reusing prop useIconRedirect to hide actions when not needed
bildvitta/asteroid pull request #458
Opened 2021-12-13 14:05 UTC by gqueiroz1

Motivação:
- Dentro de alguns casos, não iremos precisar de uma ação, apenas de uma listagem.
- Para o Vendas no Modular por exemplo, tenho uma listagem sem ações.
![image](https://user-images.githubusercontent.com/22224160/145826518-fd5afd60-c902-4f21-9c21-ab18ed2afed8.png)

Solução:
- Reutilizar a prop `useIconRedirect` para verificar a necessidade de colocar o botão na tela ou não.

2021-12-13 14:13 UTC, eliasassuncao requested changes

2021-12-13 14:13 UTC, eliasassuncao commented on ui/src/components/list-items/QasListItems.vue
> +          <q-item-section v-if="useIconRedirect" side>
na maioria dos casos acho que irá ter um redirect, então não faria mais sentido criar uma props `hideRedirectAction` pra esses casos específicos?

2021-12-13 14:16 UTC, felipegoulart requested changes

2021-12-13 14:16 UTC, felipegoulart commented on ui/src/components/list-items/QasListItems.vue
> +          <q-item-section v-if="useIconRedirect" side>
Acredito que seja melhor usar `hideIconRedirect` com `default: false` para não quebrar as aplicações que já usam esse componente.

2021-12-13 16:34 UTC, DouglasCalora requested changes

2021-12-13 16:34 UTC, DouglasCalora commented on ui/src/components/list-items/QasListItems.vue
> +          <q-item-section v-if="!useSectionActions" side>
O default é mostrar, pq esta negando?

2021-12-13 21:54 UTC, gqueiroz1 commented on ui/src/components/list-items/QasListItems.vue
> +          <q-item-section v-if="!useSectionActions" side>
corrigido

2021-12-15 18:48 UTC, leonardoMarco20 commented on ui/src/components/list-items/QasListItems.vue
> +      default: true
Aqui não precisaria passar o default pra ele, se vc usar a prop ele vai passar a ser true caso nao use ficará como false. Ou então, se ele sempre vai aparecer o melhor seria mudar o nome da prop para noSelectActions

2023-04-14 19:25 UTC, closed without merging