Feature/empty fields table grid
bildvitta/asteroid pull request #481
Opened 2022-01-17 19:08 UTC by leonardoMarco20

# Descrição
Criação de uma nova prop para a inserção de um valor customizado em casos de valores vazios. O Design decidiu alterar a forma padrão de tabelas e grids, agora quando há um valor vazio será exibido um `-`. Caso queira uma mensagem customizada poderá utilizar a prop `emptyResultValue`.

## Issues

## Tipo de alteração
- [X] Added (Novas features)
- [ ] Changed (Alterações que podem ou não haver breaking changes)
- [ ] Removed (Remoção de alguma funcionalidade, código etc)
- [ ] Fixed (Alterações para corrigir bugs etc)

## Testes
- [x] Testes em dev
- [ ] Testes automatizados

## Documentação
- [X] Documentação no storybook foi atualizada e testada?
- [ ] Caso tenha componente novo, foi criado a nova documentação?

## Checklist
- [X] Meu código segue todos os padrões de código incluindo eslint
- [X] Eu fiz um meu próprio code review antes de abrir este pull request
- [x] Eu atualizei o changelog seguindo o padrão keep changelog
- [X] Antes da alteração eu discuti sobre o pull request com o time de front end e time de design
- [X] Minhas alterações não geram erros ou warnings no console

2022-01-17 20:42 UTC, gqueiroz1 approved these changes

2022-01-19 16:52 UTC, DouglasCalora requested changes

2022-01-19 16:52 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    emptyResultValue: {
Não acha que algo como `emptyResultText` faça mais sentido?

2022-01-19 16:52 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.stories.js
> +    emptyResultValue:{
faltou espaço depois dos 2 pontos.

2022-01-19 16:52 UTC, DouglasCalora commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    emptyResultValue: {
Essa prop é usado tanto no grid quando table generator, e já existe um mixin que usam ela, pq não declarou lá para n ter que ficar reescrevendo?

2022-01-19 16:52 UTC, DouglasCalora commented on ui/src/components/table-generator/QasTableGenerator.stories.js
> +    emptyResultValue:{
faltou espaço depois dos 2 pontos.

2022-01-19 17:13 UTC, leonardoMarco20 commented on ui/src/components/table-generator/QasTableGenerator.stories.js
> +    emptyResultValue:{
corrigido

2022-01-19 17:14 UTC, leonardoMarco20 commented on ui/src/components/grid-generator/QasGridGenerator.stories.js
> +    emptyResultValue:{
corrigido

2022-01-19 17:14 UTC, leonardoMarco20 commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    emptyResultValue: {
Atualizado

2022-01-19 17:48 UTC, leonardoMarco20 commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +    emptyResultValue: {
corrigido

2022-02-16 20:46 UTC, gcarpi commented
@DouglasCalora Precisamos dessa feature em alguns lugares, seria possível aprovar ou tem alguma pendência?

2022-03-31 17:30 UTC, DouglasCalora requested changes

2022-03-31 17:31 UTC, gcarpi commented on CHANGELOG.md
> +## 2.15.1 - 2022-03-31
Perfeito, Doug! Mudança realizada, obrigado.

2022-03-31 17:59 UTC, merged