Criar Documentação das Classes
bildvitta/asteroid pull request #522
Opened 2022-04-19 20:04 UTC by RafaelM-DEv

# Descrição
Criar Documentação das Classes de Estilo

## Issues

## Tipo de alteração
- [ ] Added (Novas features)
- [ ] Changed (Alterações que podem ou não haver breaking changes)
- [ ] Removed (Remoção de alguma funcionalidade, código etc)
- [ ] Fixed (Alterações para corrigir bugs etc)

## Testes
- [ ] Testes em dev
- [ ] Testes automatizados

## Documentação
- [ ] Documentação no storybook foi atualizada e testada?
- [ ] Caso tenha componente novo, foi criado a nova documentação?

## Checklist
- [ ] Meu código segue todos os padrões de código incluindo eslint
- [ ] Eu fiz um meu próprio code review antes de abrir este pull request
- [ ] Eu atualizei o changelog seguindo o padrão keep changelog
- [ ] Antes da alteração eu discuti sobre o pull request com o time de front end e time de design
- [ ] Minhas alterações não geram erros ou warnings no console

2022-04-19 20:07 UTC, DouglasCalora requested changes

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/assets/menu.js
> +    name: 'Variáveis CSS',
Estilos

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/assets/menu.js
> +        path: '/styles/background/background'
`/styes/background`

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/pages/styles/background/background.md
> +
espaço atoa?

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/pages/styles/background/background.md
> +
pq tem 2 espaços?

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/pages/styles/background/background.md
> +
pq tem 2 espaços?

2022-04-19 20:07 UTC, DouglasCalora commented on docs/src/pages/styles/background/background.md
> +|`bg-position-top`   |Posiciona a imagem de fundo na parte superior do container |`background-position: top`   |
não precisa de um espaço entre `|Posiciona`?

2022-04-19 20:21 UTC, RafaelM-DEv commented on docs/src/pages/styles/background/background.md
> +
removido

2022-04-19 20:22 UTC, RafaelM-DEv commented on docs/src/pages/styles/background/background.md
> +
removido

2022-04-19 20:22 UTC, RafaelM-DEv commented on docs/src/pages/styles/background/background.md
> +
removido

2022-04-19 20:26 UTC, RafaelM-DEv commented on docs/src/assets/menu.js
> +    name: 'Variáveis CSS',
feito

2022-04-19 20:26 UTC, RafaelM-DEv commented on docs/src/assets/menu.js
> +        path: '/styles/background/background'
feito

2022-04-19 20:26 UTC, RafaelM-DEv commented on docs/src/pages/styles/background/background.md
> +|`bg-position-top`   |Posiciona a imagem de fundo na parte superior do container |`background-position: top`   |
só por estética no código

2022-04-25 17:41 UTC, DouglasCalora requested changes

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/border-radius.md
> +
remover

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/border-radius.md
> +`*$generic-border-radius` : tem valor padrão definido pelo Quasar.
qual? é melhor ja deixar aqui, fazer a pessoa ir até o quasar pra ver, sendo que poderia ja estar aqui

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/line-height.md
> +---
espaço

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/border.md
> +---
espaço

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/background.md
> +---
espaço

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/container.md
> +```js
deixa um `## Definição`, para saber que isto é a definição da classe

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/set-brand.md
> +---
espaço

2022-04-25 17:41 UTC, DouglasCalora commented on docs/src/pages/styles/text.md
> +---
espaço

2022-04-25 18:00 UTC, RafaelM-DEv commented on docs/src/pages/styles/border-radius.md
> +
remoivido

2022-04-25 18:05 UTC, RafaelM-DEv commented on docs/src/pages/styles/border-radius.md
> +`*$generic-border-radius` : tem valor padrão definido pelo Quasar.
Feito

2022-04-25 18:06 UTC, RafaelM-DEv commented on docs/src/pages/styles/line-height.md
> +---
Feito

2022-04-25 18:06 UTC, RafaelM-DEv commented on docs/src/pages/styles/border.md
> +---
Feito

2022-04-25 18:07 UTC, RafaelM-DEv commented on docs/src/pages/styles/background.md
> +---
Feito

2022-04-25 18:07 UTC, RafaelM-DEv commented on docs/src/pages/styles/container.md
> +```js
Feito

2022-04-25 18:08 UTC, RafaelM-DEv commented on docs/src/pages/styles/set-brand.md
> +---
Feito

2022-04-25 18:08 UTC, RafaelM-DEv commented on docs/src/pages/styles/text.md
> +---
Feito

2022-04-25 18:21 UTC, DouglasCalora approved these changes

2022-04-25 19:05 UTC, merged