Feature/signature-pad-size
bildvitta/asteroid pull request #529
Opened 2022-04-26 19:17 UTC by felipegoulart

# Descrição
Usuários estavam com dificuldade em fazer a assinatura em dispositiveis móveis.
Foi definido junto com a designer que o componente terá tamanhos padrões de acordo com o tamanho da tela. 

## Issues

## Tipo de alteração
- [x] Added (Novas features)
- [ ] Changed (Alterações que podem ou não haver breaking changes)
- [ ] Removed (Remoção de alguma funcionalidade, código etc)
- [ ] Fixed (Alterações para corrigir bugs etc)

## Testes
- [ ] Testes em dev
- [ ] Testes automatizados

## Documentação
- [ ] Documentação no storybook foi atualizada e testada?
- [ ] Caso tenha componente novo, foi criado a nova documentação?

## Checklist
- [ ] Meu código segue todos os padrões de código incluindo eslint
- [ ] Eu fiz um meu próprio code review antes de abrir este pull request
- [ ] Eu atualizei o changelog seguindo o padrão keep changelog
- [ ] Antes da alteração eu discuti sobre o pull request com o time de front end e time de design
- [ ] Minhas alterações não geram erros ou warnings no console

2022-04-26 19:54 UTC, DouglasCalora requested changes
No PR ele gera um template para seguir, lá não foi marcado sobre a documentação, precisa documentar a nova prop adicionada.

2022-04-26 19:54 UTC, DouglasCalora commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    }
Ta bem repetitivo esta parte, e se fizer algo assim:

```js
size () {
  const sizes = {
    [this.$_isSmall]: { width: '264', height: '250' },
    [this.$_isMedium]: { width: '576', height: '420' },
    [this.$_isLarge]: { width: '350', height: '250' },
  }

  return sizes[true]
}
```
Assim vc poderia passar com v-bind.
Outra coisa, bem especifico esses valores, não acha?

2022-04-26 20:01 UTC, eliasassuncao requested changes

2022-04-26 20:01 UTC, felipegoulart commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +    }
os valores foram definidos com teste em telas de diferentes tamanhos

2022-04-26 20:02 UTC, felipegoulart commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +      return sizes[true]
Foi definido que terá um tamanho fixo para o pad para manter uma padronização.

2022-04-26 20:03 UTC, felipegoulart commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +import { screenMixin } from '../../mixins'
Não, eu testei. `src/mixins` também não funciona

2022-04-26 20:04 UTC, felipegoulart commented on ui/src/components/signature-pad/QasSignaturePad.vue
> +        [this.$_isSmall]: '264',
Vou alinhar as medidas exatas com a designer

2022-04-27 19:48 UTC, DouglasCalora approved these changes

2022-04-27 20:38 UTC, eliasassuncao requested changes

2022-04-27 20:38 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    padContainerWidth () {
não seria melhor `signaturePadWidth` ?

2022-04-27 20:38 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +    padHeight () {
não seria melhor `signaturePadHeight` ?

2022-04-27 20:53 UTC, eliasassuncao approved these changes

2022-04-27 21:13 UTC, DouglasCalora approved these changes

2022-04-27 21:14 UTC, merged