Feature/next/beta 10
bildvitta/asteroid pull request #542
Opened 2022-05-19 20:59 UTC by DouglasCalora

# Descrição
Inclua uma pequena descrição explicando o motivo do pull request

## Issues

## Tipo de alteração
- [ ] Added (Novas features)
- [ ] Changed (Alterações que podem ou não haver breaking changes)
- [ ] Removed (Remoção de alguma funcionalidade, código etc)
- [ ] Fixed (Alterações para corrigir bugs etc)

## Testes
- [ ] Testes em dev
- [ ] Testes automatizados

## Documentação
- [ ] Documentação no storybook foi atualizada e testada?
- [ ] Caso tenha componente novo, foi criado a nova documentação?

## Checklist
- [ ] Meu código segue todos os padrões de código incluindo eslint
- [ ] Eu fiz um meu próprio code review antes de abrir este pull request
- [ ] Eu atualizei o changelog seguindo o padrão keep changelog
- [ ] Antes da alteração eu discuti sobre o pull request com o time de front end e time de design
- [ ] Minhas alterações não geram erros ou warnings no console

2022-05-19 21:39 UTC, eliasassuncao requested changes

2022-05-19 21:39 UTC, eliasassuncao commented on docs/src/examples/QasActionsMenu/Delete.vue
> +      alert('fui deletado com sucesso!')
não deveriamos usar o notify do asteroid ?

2022-05-19 21:39 UTC, eliasassuncao commented on docs/src/examples/QasFormView/Edit.vue
> +    <qas-form-view v-model="values" v-model:errors="errors" v-model:fields="fields" :cancel-route="cancelRoute" :custom-id="customId" :entity="entity" mode="replace" :use-boundary="false" @submit-suc
oq seria esse comentário  `<!-- Descartar essa div -->` ?

2022-05-19 21:39 UTC, eliasassuncao commented on docs/src/examples/QasInput/Basic.vue
> +    <qas-input v-model="model" :error="true" label="Meu input!" />
passando somente `error` não funciona?

2022-05-19 21:39 UTC, eliasassuncao commented on ui/src/components/input/QasInput.vue
> +    unmaskedValue: {
deveria usar use aqui?

2022-05-19 23:14 UTC, gcarpi approved these changes

2022-05-20 13:01 UTC, DouglasCalora commented on ui/src/components/input/QasInput.vue
> +    unmaskedValue: {
Não, pq é assim que o quasar chama

2022-05-20 13:04 UTC, DouglasCalora commented on docs/src/examples/QasSelect/Searchable.vue
> +      <qas-select v-model="model" label="Meu select!" :options="options" use-search />
Então, na minha visão deve ser padrão para select com muitas opções, podemos fazer uma logica com base nas options `:use-search: options.length > 6` algo assim, precisaria discutir com os designers.

2022-05-20 13:50 UTC, DouglasCalora commented on ui/src/components/app-bar/QasAppBar.vue
> +        <div v-if="hasUser" class="cursor-pointer items-center q-mr-sm qas-app-bar__user rounded-borders row text-grey-9" :title="user.name || user.givenName">
substituído por `userName`

2022-05-20 14:46 UTC, DouglasCalora commented on docs/src/examples/QasFormView/Edit.vue
> +    <qas-form-view v-model="values" v-model:errors="errors" v-model:fields="fields" :cancel-route="cancelRoute" :custom-id="customId" :entity="entity" mode="replace" :use-boundary="false" @submit-suc
Como foi feito, na hora de copiar o código, precisa descartar essa div e usar somente o que tem dentro do qas-form-view

2022-05-20 14:56 UTC, gcarpi commented on docs/src/examples/QasSelect/Searchable.vue
> +      <qas-select v-model="model" label="Meu select!" :options="options" use-search />
Ótima ideia essa hein

2022-05-20 14:58 UTC, gcarpi approved these changes

2022-05-20 14:59 UTC, eliasassuncao approved these changes

2022-05-20 16:26 UTC, merged