Support/some small fixes
bildvitta/asteroid pull request #583
Opened 2022-07-27 19:40 UTC by gcarpi

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `main`.
- [ ] v3 -> a partir da branch `next`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-07-28 14:45 UTC, eliasassuncao requested changes

2022-07-28 14:45 UTC, eliasassuncao commented on docs/src/layouts/DocLayout.vue
> -  <q-layout class="app" view="doc-layout lHh LpR lff">
as classes estão fora do padrão não? se chama `DocLayout` e estão usando as classes como `app`

2022-07-28 14:45 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
> +        }
`result && Object.assign(modelValue, result)`

2022-07-28 14:45 UTC, eliasassuncao commented on ui/src/components/select/QasSelect.vue
> +      type: [Array, Object, String, Number, Boolean]
faz sentido ter um campo select boolean? normalmente pra campos boolean utilizamos toggle

2022-07-29 16:09 UTC, gcarpi commented on docs/src/layouts/DocLayout.vue
> -  <q-layout class="app" view="doc-layout lHh LpR lff">
Qual seria o padrão? `doc-layout`? 🤔

2022-07-29 16:10 UTC, gcarpi commented on ui/src/components/form-view/QasFormView.vue
> +        }
Boaa!

2022-07-29 16:12 UTC, gcarpi commented on ui/src/components/select/QasSelect.vue
> +      type: [Array, Object, String, Number, Boolean]
É mais comum ser utilizado o `toggle` mesmo, mas podemos dar a possibilidade de usar o Select também, não vejo motivo para limitar essa possibilidade...

Mas foi um requisito de algo que o Doug estava precisando, talvez ele pode explicar melhor a necessidade. @DouglasCalora

2022-07-29 17:16 UTC, gcarpi commented on docs/src/layouts/DocLayout.vue
> -  <q-layout class="app" view="doc-layout lHh LpR lff">
Definido que por enquanto seguirá da maneira que está.

2022-07-29 17:25 UTC, eliasassuncao approved these changes

2022-08-01 19:52 UTC, DouglasCalora approved these changes

2022-08-01 19:52 UTC, merged