data cy
bildvitta/asteroid pull request #601
Opened 2022-09-01 13:24 UTC by Lourengato

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `main-homolog`.
- [x] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-09-01 16:15 UTC, leonardoMarco20 commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +      <slot :field="slotValue[key]" :name="`field-${field.name}`" >
Foi adicionado um espacinho no final da tag

2022-09-01 19:01 UTC, gcarpi requested changes

2022-09-01 19:01 UTC, gcarpi commented on ui/src/components/list-view/QasListView.vue
> +        <qas-filters v-bind="filtersProps" :entity="entity" data-cy="search-input" />
Vê se faz sentido, o `qas-filters` não é só o input de search, não deveria estar o `data-cy` dentro do próprio componente `QasFilters`?

E dentro do componente, eu acredito que já seria legal acrescentar o `data-cy` em todos os possíveis campos do filtro + input de search.

2022-09-01 19:04 UTC, Lourengato commented on ui/src/components/grid-generator/QasGridGenerator.vue
> +          <header :class="headerClass" :data-cy="`${field.name}-field`">{{ field.label }}</header>
o padrão do cypress é esse, tinha colocado assim primeiro e mudei depois https://www.bigbinary.com/books/learn-qa-automation-using-cypress/data-cy-conventions

2022-09-01 19:10 UTC, Lourengato commented on ui/src/components/list-view/QasListView.vue
> +        <qas-filters v-bind="filtersProps" :entity="entity" data-cy="search-input" />
faz sentido, vou mudar aqui

2022-09-02 13:26 UTC, DouglasCalora requested changes
Eu acho que seria bom adicionar o prefixo do componente, o que acha?
`filters-search-input`
`filters-btn`
etc
E faltou changelog

2022-09-02 19:45 UTC, DouglasCalora approved these changes

2022-09-02 19:51 UTC, gcarpi approved these changes

2022-09-02 19:53 UTC, merged