Feature/main homolog/new notify styles
bildvitta/asteroid pull request #651
Opened 2022-12-07 15:39 UTC by eliasassuncao

Mudança na estilização dos notifies, incluindo posição de exibição, cor, botão de fechar e ícones.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [x] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-07 20:35 UTC, leonardoMarco20 approved these changes

2022-12-07 23:01 UTC, gcarpi requested changes

2022-12-07 23:01 UTC, gcarpi commented on ui/src/plugins/notify-success/NotifySuccess.js
> +  const marginValues = `margin-top: ${Screen().untilMedium ? '40px' : '80px'};`
Vi que algumas coisas se repetem na configuração do Notify, seria interessante nós criamos um wrapper do Notify do Quasar? E nesse wrapper a gente pode ter as configurações default...

2022-12-08 14:39 UTC, eliasassuncao commented on CHANGELOG.md
> +## Unreleased
feito

2022-12-08 14:55 UTC, eliasassuncao commented on ui/src/css/components/notification.scss
> +  &__content .q-icon {
feito

2022-12-08 14:56 UTC, eliasassuncao commented on ui/src/plugins/notify-error/NotifyError.js
> +      style: marginValues
feito

2022-12-15 17:21 UTC, merged