feat(Mixins): changed gutter value
bildvitta/asteroid pull request #652
Opened 2022-12-07 20:02 UTC by eliasassuncao

Foi alterado o valor do gutter com base no DS

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [x] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-07 22:49 UTC, gcarpi commented on CHANGELOG.md
> +## Unreleased
Aqui é "Não publicado", o Asteroid lida diferente do que no Modular.

2022-12-08 14:34 UTC, eliasassuncao commented on CHANGELOG.md
> +## Unreleased
feito

2022-12-12 16:21 UTC, DouglasCalora requested changes
Está com conflitos.

2022-12-12 16:21 UTC, DouglasCalora commented on CHANGELOG.md
> +- `generator.js` - Modificado o padrão da props de gutter de `md` para `lg`.
da prop `gutter`

2022-12-12 16:21 UTC, DouglasCalora commented on ui/src/mixins/generator.js
> +      default: 'lg',
Este mixin é utilizado tanto no `QasFormGenerator` quanto no `QasGridGenerator`, faltou atualizar os arquivos de docs (.yml) deles.

2022-12-13 14:55 UTC, eliasassuncao commented on ui/src/mixins/generator.js
> +      default: 'lg',
feito

2022-12-13 14:55 UTC, eliasassuncao commented on CHANGELOG.md
> +- `generator.js` - Modificado o padrão da props de gutter de `md` para `lg`.
feito

2022-12-13 20:47 UTC, DouglasCalora approved these changes

2022-12-14 14:40 UTC, merged