Feature/main homolog/cu 3eh5485
bildvitta/asteroid pull request #657
Opened 2022-12-09 18:28 UTC by caiotarifa

Utilização do QasActionsMenu dentro do nested para reaproveitar a estilização/comportamentos do componente e corresponder as necessidades do time de design.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-09 18:28 UTC, caiotarifa commented
Task linked: [CU-3eh5485 Modificar o QasNestedFields para utilizar o QasActionsMenu](https://app.clickup.com/t/3eh5485)

2022-12-10 14:02 UTC, gcarpi requested changes

2022-12-10 14:02 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    actionsList (index, row) {
Seria possível o `QasNestedFields` receber uma propriedade que contenha ações que serão repassadas para o `QasActionsMenu`? Pois vamos necessitar passar algumas ações além do Duplicar/Remover em alguns lugares no projeto do CRM...

Seria interessante que ele aceitasse uma propriedade parecida (ou se não igual) com a `list` do `QasActionsMenu`:
![Screen Shot 2022-12-10 at 10 53 26](https://user-images.githubusercontent.com/19765074/206858800-a4d1463a-c975-4de9-a8ed-c28630660c53.jpg)

Seria legal também que essas ações passadas por meio dessa prop `list` sejam concatenadas com a `duplicate` e `destroy`, ou seja, essa propriedade não substituiria as ações padrões do componente `QasNestedFields`.

PS: Ah, e eu deveria ter previsto isso lá na atividade criada no Clickup, pois foi algo que vimos no refinamento do CRM, mas me esqueci de repassar para a atividade. 😢

2022-12-10 14:02 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +                <qas-actions-menu v-if="hasBlockActions(row)" ref="actionsMenu" :list="actionsList(index, row)" />
Acredito que o ref `actionsMenu` não está sendo utilizado

2022-12-10 22:54 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +    actionsList (index, row) {
De fato, não tinha me atentado ao modo `inline`, pela minha pesquisa nos projetos que possuo acesso, o único projeto utilizando esse modo atualmente é o AT e o Jurídico (que será refeito). 

Mas acredito que o melhor seria realmente realizar esse alinhamento com o time de design.

2022-12-15 13:23 UTC, gcarpi commented on CHANGELOG.md
> +- `QasActionsMenu`: removido componente privado `PvActionsMenusList` e adicionado o código internamente.
Será que precisa dessa linha? Pois o `PvActionsMenusList` ainda nem tinha ido pra nenhuma versão...

2022-12-15 13:23 UTC, gcarpi commented on ui/src/components/actions-menu/QasActionsMenu.vue
> +        props.icon = this.hasDelete ? icon : this.list[this.firstItemKey]?.icon
Por que não utilizar a computada `actions` invés da prop `list`? Aí não precisaria fazer esse tratamento, pois as actions já contempla o `delete`...

2022-12-15 13:23 UTC, gcarpi commented on ui/src/components/actions-menu/QasActionsMenu.yml
>      type: String
Precisa adicionar a prop `useLabelOnSmallScreen` aqui na doc

2022-12-15 14:03 UTC, eliasassuncao requested changes

2022-12-15 14:03 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
> +        enterActiveClass: 'animated slideInDown'
classe em camelCase?

2022-12-16 12:58 UTC, DouglasCalora approved these changes

2022-12-16 12:59 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasActionsMenu`: removido propriedade `label`, agora o label sempre será fixo "Opções".
Definido com designer que sempre será options

2022-12-16 12:59 UTC, merged