Add option to QasNestedFields starts empty.
bildvitta/asteroid pull request #658
Opened 2022-12-10 14:35 UTC by caiotarifa

O novo comportamento deve trazer um texto para que o usuário clique e para só então exibir os campos do nested.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-10 14:35 UTC, caiotarifa commented
Task linked: [CU-3eh505r Alteração do comportamento quando os campos são opcionais no QasNestedFields](https://app.clickup.com/t/3eh505r)

2022-12-10 23:34 UTC, gcarpi requested changes

2022-12-10 23:34 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      default: true,
Será que precisamos reportar como uma breaking change em relação ao novo comportamento padrão no CHANGELOG? 🤔  

Sei que no sentido semântico da coisa não faz muito sentido, pois não insere nenhuma breaking change de fato no código, mas acredito que faça sentido o "alerta" para que os desenvolvedores se adequem ao novo padrão ou passe a usar o `useStartsEmpty` como `false` onde acreditarem ser o mais correto. Como, por exemplo, quando os campos do nested são de fato algo importante de serem exibidos por padrão.

2022-12-10 23:34 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      default: true
**Dúvida:** Será que seria interessante o default ser dessa propriedade ser baseada no valor da propriedade `useFirstInputButton`?

**Ex:** 
Eu penso que se queremos exibir os campos por padrão na tela (`useFirstInputButton` = `false`), muito provavelmente não vamos querer que o usuário possa remover o último item do nested, pois pode ser que pelo menos um item seja obrigatório ser preenchido. Levando isso em consideração, penso que a propriedade `useDestroyAlways` (quando não passada) pode ser um espelho da `useFirstInputButton`, mantendo o mesmo comportamento padrão atual.

2022-12-10 23:34 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.yml
> +    type: Boolean
O type aqui seria `String`.

2022-12-10 23:34 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.yml
>      type: Boolean
O type aqui seria `String`.

2022-12-12 13:10 UTC, gcarpi requested changes

2022-12-12 13:10 UTC, gcarpi commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      default: true,
Dúvida: Por que precisa dessa propriedade? Não poderia utilizar a `useFirstInputButton` para fazer esse controle?

2022-12-15 21:40 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
> +            <qas-btn class="q-px-sm" color="dark" flat @click="add()">{{ addFirstInputLabel }}</qas-btn>
não precisa do `()`

2022-12-15 21:40 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
>                <qas-input class="disabled no-pointer-events" hide-bottom-space :label="addInputLabel" outlined @focus="add()" />
não precisa do `()`

2022-12-15 21:40 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
> +            <qas-btn class="q-px-sm" color="dark" flat icon="o_add" @click="add()">{{ addInputLabel }}</qas-btn>
não precisa do `()`

2022-12-15 21:40 UTC, eliasassuncao commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      default: undefined
type boolean mas default undefined?

2022-12-15 22:30 UTC, gcarpi approved these changes

2022-12-16 12:25 UTC, merged

2022-12-16 12:25 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +      default: undefined
explicado no discord

2022-12-16 12:25 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
> +            <qas-btn class="q-px-sm" color="dark" flat icon="o_add" @click="add()">{{ addInputLabel }}</qas-btn>
explicado no discord

2022-12-16 12:25 UTC, DouglasCalora commented on ui/src/components/nested-fields/QasNestedFields.vue
>                <qas-input class="disabled no-pointer-events" hide-bottom-space :label="addInputLabel" outlined @focus="add()" />
explicado no discord