feat(QasListView): Changes in pagination
bildvitta/asteroid pull request #660
Opened 2022-12-12 21:06 UTC by DouglasCalora

Adicionado `QasPagination` no `QasListView` e algumas alterações referentes a paginação.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [x] Sim
- [ ] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-12 21:11 UTC, caiotarifa requested changes

2022-12-12 21:11 UTC, caiotarifa commented on ui/src/components/list-view/QasListView.vue
> +            Itens por página: {{ results.length }}
Não faz sentido, não é a quantidade de itens na página mas sim a quantidade de itens por página. Por exemplo, na última página poderiam ter apenas 2 itens, enquanto o normal é ter 12.

O valor aqui precisa ser o mesmo do `perPage` (Vuex).

2022-12-12 21:25 UTC, eliasassuncao approved these changes

2022-12-12 21:36 UTC, gcarpi approved these changes

2022-12-12 21:43 UTC, DouglasCalora commented on ui/src/components/list-view/QasListView.vue
> +            Itens por página: {{ results.length }}
Mas qual o sentido de mostrar o tanto que pode ter? Não uma informação irrelevante? E eu tinha alinhado com o yan e ele disse que era com base nos resultados.

2022-12-12 21:51 UTC, DouglasCalora commented on ui/src/components/list-view/QasListView.vue
> +            Itens por página: {{ results.length }}
Conversando com o @waguerrero e @gcarpi achamos que faz mais sentido mostrar informação referente ao `count` ex: `Exibindo 10 registros de 120`, sendo "10" referente ao results e "120" ao count, o que acha?

2022-12-13 20:43 UTC, DouglasCalora commented on ui/src/components/list-view/QasListView.vue
> +            Itens por página: {{ results.length }}
@caiotarifa Levei a ideia para o pessoal do design e ficou definido que não vai mais ter nenhum label na vdd, apenas paginação na direita.

2022-12-13 20:45 UTC, merged