Feature/add-filter-props
bildvitta/asteroid pull request #662
Opened 2022-12-15 23:16 UTC by felipegoulart

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `main`.
- [ ] v3 -> a partir da branch `next`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-16 16:19 UTC, DouglasCalora requested changes

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +        const cachedOptions = this.fieldsProps?.[key]?.cachedOptions || []
isto não é um cached, ela esta sendo reescrita toda vez que o loop é refeito.

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +          field.options = [...field.options, ...cachedOptions]
.push não resolve?

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +      deep: true,
precisa do deep?

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +    this.$emit('input', this.context.filters)
pq a necessidade disto?

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +      this.$nextTick(() => {
sem o nextTick não funciona?

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.vue
> +      type: [Array, Object, String, Number, Boolean]
documentou?

2022-12-16 16:19 UTC, DouglasCalora commented on ui/src/components/filters/QasFilters.vue
> +        if (!filters[key]?.length || isNil(filters[key])) {
Pq esse length? Usamos muito o lodash na v2 do asteroid para compensar utilizar?

2022-12-16 16:34 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +          field.options = [...field.options, ...cachedOptions]
`.concat` fica melhor ainda

2022-12-16 16:36 UTC, felipegoulart commented on ui/src/components/select/QasSelect.vue
> +      type: [Array, Object, String, Number, Boolean]
Documentado

2022-12-16 16:36 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +          field.options = [...field.options, ...cachedOptions]
Feito

2022-12-16 16:40 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +        if (!filters[key]?.length || isNil(filters[key])) {
`!filters[key]?.length` substituído por `isEmpty(filters[key])`, para validar quando um array é vazio e não permanecer no filters, quebrando as badges

Lodash tem bastante uso dentro do V2.

2022-12-16 17:08 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +      this.$nextTick(() => {
funciona. removido

2022-12-16 17:09 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +    this.$emit('input', this.context.filters)
Precisa atualizar o model assim que o componente é carregado

2022-12-16 17:10 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +      deep: true,
Precisa, se não, ele não capta as mudanças em uma chave específica

2022-12-16 17:11 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +          field.options = [...field.options, ...cachedOptions]
Fiz alguns testes com `concat` e `push`, ambos não funcionaram. `push` teve um agravante que era um loop infinito no componente e não encontrei o motivo

2022-12-16 17:11 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +        const cachedOptions = this.fieldsProps?.[key]?.cachedOptions || []
qual seria um nome mais apropriado?

2022-12-16 19:10 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +        const cachedOptions = this.fieldsProps?.[key]?.cachedOptions || []
removido

2022-12-16 19:10 UTC, felipegoulart commented on ui/src/components/filters/QasFilters.vue
> +          field.options = [...field.options, ...cachedOptions]
removido

2022-12-19 13:34 UTC, eliasassuncao requested changes

2022-12-19 13:34 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasFielters`: added conditional to check if filter value is empty array, undefined or null in `updateValues`.
não seria `QasFilters` ?

2022-12-19 13:35 UTC, felipegoulart commented on CHANGELOG.md
> +- `QasFielters`: added conditional to check if filter value is empty array, undefined or null in `updateValues`.
corrigido

2023-02-08 18:21 UTC, eliasassuncao approved these changes

2023-02-08 19:00 UTC, DouglasCalora requested changes
Foi testado todos os componentes um a um? Visto que temos bastante atualização de libs...

2023-02-08 19:00 UTC, DouglasCalora commented on CHANGELOG.md
> +
Faltou documentar sobre as libs atualizadas.

2023-02-08 20:43 UTC, closed without merging