New Layout 🏆
bildvitta/asteroid pull request #665
Opened 2022-12-19 04:32 UTC by caiotarifa

Desenvolvimento do novo layout base para o design System.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [x] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-20 19:06 UTC, DouglasCalora requested changes

2022-12-20 19:06 UTC, DouglasCalora commented on ui/src/index.scss
> +  --qas-generic-border-radius: 4px;
radius padrão vai se manter 4px

2022-12-21 00:42 UTC, caiotarifa commented on ui/src/components/app-menu/QasAppMenu.vue
>    }
Não entendi... tentei ser ao máximo ser fiel ao layout.

2022-12-21 00:43 UTC, caiotarifa commented on ui/src/components/app-menu/QasAppMenu.vue
>    }
Idem.

2022-12-21 00:44 UTC, caiotarifa commented on ui/src/components/app-menu/QasAppMenu.vue
> +    line-height: 1.25;
Eu preciso mudar esse valor para aparecer de uma forma diferente quando o QasAppUser for chamado dentro do QasAppMenu. Pois tem um outro `line-height` normalmente (no QasAppBar).

Alguma sugestão?

2022-12-21 00:45 UTC, caiotarifa commented on ui/src/components/app-menu/QasAppMenu.yml
> +      "
1. É uma string.
2. Copiei do `QasAppBar.yml`.

2022-12-21 00:46 UTC, caiotarifa commented on ui/src/components/app-bar/QasAppBar.vue
> +      default: '',
Não precisa.

2022-12-21 00:47 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +export default {
Pronto.

2022-12-21 00:48 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +  }
Eu sei o mesmo valor de tamanho do `.caption`, porém não posso mudar o `line-height` e o `font-weight`.

Algua sugestão?

2022-12-21 00:49 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +  }
Idem.

2022-12-21 00:49 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +  }
Idem.

2022-12-21 00:49 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +    font-size: 1.125rem;
Idem, mas o mesmo valor do `h4`.

2022-12-21 00:51 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +    font-size: 1rem;
Esse ta errado, removi.

2022-12-21 00:55 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +    }
Já estava assim (mas no QasAppBar). É mais leve usar CSS, mas se achar melhor podemos fazer com `v-if`.

2022-12-21 00:56 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.vue
> +    line-height: 1.1;
Idem.

2022-12-21 00:56 UTC, caiotarifa commented on ui/src/components/app-user/QasAppUser.yml
> +      "
Idem.

2022-12-21 00:57 UTC, caiotarifa commented on ui/src/css/components/shadow.scss
> +}
Estou removendo, mas com o sentimento de ter que voltar logo, pois o que temos está grosseiro.

2022-12-21 01:27 UTC, caiotarifa commented on ui/src/index.scss
> +  --qas-generic-border-radius: 4px;
Não entendi? Então está certo?

2022-12-21 13:56 UTC, caiotarifa commented on ui/src/index.scss
> +  --qas-generic-border-radius: 4px;
Conforme conversamos, vai se manter `8px`. Resolvido!

2022-12-22 17:47 UTC, merged