Changed default prop `cancelButtonLabel` from QasFormView
bildvitta/asteroid pull request #669
Opened 2022-12-19 21:10 UTC by DouglasCalora

- `QasFormView`: alterado valor default da propriedade `cancelButtonLabel` de "Cancelar" para "Voltar".
clickup: https://app.clickup.com/t/864dhud5n

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2022-12-19 21:54 UTC, gcarpi approved these changes

2022-12-19 21:55 UTC, eliasassuncao requested changes

2022-12-19 21:55 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
> +      default: 'Voltar',
e o comportamento do botão? como vai funcionar?

2022-12-20 12:38 UTC, DouglasCalora commented on ui/src/components/form-view/QasFormView.vue
> +      default: 'Voltar',
Mesma coisa, apenas o label.

2022-12-20 19:28 UTC, merged