Password Input Documentation
bildvitta/asteroid pull request #70
Opened 2021-01-14 15:16 UTC by Lourengato

Closes #30

2021-01-14 17:28 UTC, DouglasCalora requested changes

2021-01-14 17:28 UTC, DouglasCalora commented on ui/src/components/password-input/QasPasswordInput.stories.js
> +  title: 'Components/PasswordInput',
espaço depois do titulo

2021-01-14 17:28 UTC, DouglasCalora commented on ui/src/components/password-input/QasPasswordInput.vue
> +      <qas-password-strength-checker v-bind="$props" @password-success="onSuccess" />
n deveria estar importando qas-password-strength-checker?

2021-01-15 16:41 UTC, Lourengato commented on ui/src/components/password-input/QasPasswordInput.stories.js
> +  title: 'Components/PasswordInput',
dar mais espaço ou tirar espaço?

2021-01-15 16:41 UTC, Lourengato commented on ui/src/components/password-input/QasPasswordInput.vue
> +      <qas-password-strength-checker v-bind="$props" @password-success="onSuccess" />
aqui não precisou, rodou normal sem importar

2021-01-21 20:27 UTC, merged