Feature/main homolog/new button
bildvitta/asteroid pull request #719
Opened 2023-02-01 17:10 UTC by DouglasCalora

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-02-01 18:58 UTC, eliasassuncao approved these changes
aprovado

2023-02-01 18:58 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasListItems`: adicionado nova propriedade `icon` para repassar o nom do ícone.
correto seria "nome" não?

2023-02-01 18:58 UTC, eliasassuncao commented on CHANGELOG.md
> +- `QasActionsMenu`: recebendo propriedade `color` dentro dos itens do `list`, que sobrepõe a propriedade `color`, porém só é usado quando existe apenas um único item na listam.
o correto seria "lista"

2023-02-01 18:58 UTC, eliasassuncao commented on docs/src/examples/QasNestedFields/InlineActions.vue
> +        }
não poderia remover esse comentário?

2023-02-01 18:58 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
> +    width: 100%;
poderia utilizar a classe `full-width` direto no botão?

2023-02-01 20:53 UTC, DouglasCalora commented on docs/src/examples/QasNestedFields/InlineActions.vue
> +        }
removido já

2023-02-01 20:53 UTC, DouglasCalora commented on ui/src/components/form-view/QasFormView.vue
> +    width: 100%;
tanto faz neste caso, aqui fica mais organizado

2023-02-02 01:06 UTC, gcarpi requested changes

2023-02-02 01:06 UTC, gcarpi commented on ui/src/css/components/button.scss
> +    &-icon-only {
Como está se repetindo esse bloco do `icon-only` para o `primary`, `secondary` & `tertiary`, compensaria condensar esses estilos?

_Ex:_
```
  &--primary, &--secondary, &--tertiary {
    &-icon-only {
      height: 48px !important;
      min-width: auto !important;
      padding: 0 !important;
      width: 48px !important;
    }
  }

  &--tertiary {
    &-icon-only {
      height: 24px !important;
      width: 24px !important;
    }
  }
 ```

2023-02-02 13:51 UTC, DouglasCalora commented on ui/src/components/form-view/QasFormView.vue
> +    min-width: 132px;
Pq com grid não ficava do tamanho correto... e sim, no no mobile ele fica full-width quem faz o controle  é o `QasAction` e ele tem o `width: 100%;`

2023-02-02 13:51 UTC, DouglasCalora commented on ui/src/components/form-view/QasFormView.vue
> +    min-width: 132px;
Pq com grid não ficava do tamanho correto... e sim, no no mobile ele fica full-width quem faz o controle  é o `QasAction` e ele tem o `width: 100%;`

2023-02-02 13:51 UTC, DouglasCalora commented on ui/src/components/btn/QasBtn.vue
> +        class: [this.classes, externalClass]
Esta errado no docs

2023-02-02 14:17 UTC, DouglasCalora commented on ui/src/css/components/button.scss
> +    &-icon-only {
neste seu exemplo eu estaria sobrescrevendo classes, oq não é legal, vou fazer esta logica somente com primary e secondary

2023-02-02 14:26 UTC, gcarpi approved these changes

2023-02-02 14:32 UTC, merged