QasActionsMenu / QasDelete / QasBtnDropdown / Delete.js / QasNestedFields
bildvitta/asteroid pull request #739
Opened 2023-03-02 22:01 UTC by DouglasCalora

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [x] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [x] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [x] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [x] Sim
- [ ] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-03-02 23:00 UTC, eliasassuncao requested changes

2023-03-02 23:00 UTC, eliasassuncao commented on ui/src/components/actions-menu/QasActionsMenu.yml
> +    desc: propriedade para definir o slipt, habilita 2 ações diferentes no mesmo componente, separando o mesmo por uma barra, o valor deve ser alguma chave (key) existente na propriedade "list".
corrigir pra `split`

2023-03-03 12:40 UTC, DouglasCalora commented on docs/src/pages/components/actions-menu.md
> +  - variant
Quando vc faz uma quebra de linha ela não se aplica ao markdown, mas realmente deu esse espaço entre eles, mas acho que não tem o que fazer.

2023-03-03 12:42 UTC, DouglasCalora commented on docs/src/pages/components/actions-menu.md
> +- Quando usado o evento @click no componente, caso esteja habilitado o slit, o @click vai pegar no click do ícone a direita e não no botão a esquerda, caso o slot não esteja habilitado, o @click pega
Sim seria split, e não neste caso acho que faz mais sentido ser virgula.

2023-03-03 12:47 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasBtnDropdown`: adicionado novo componente semelhante ao QBtnDropdown, porém nossas regras, e estilos.
Como assim?

2023-03-03 12:48 UTC, DouglasCalora commented on docs/src/examples/QasBtnDropdown/ExWithClickEvent.vue
> +    <qas-label class="q-mt-lg" label="Evento click sem split" />
Sim, para mostrar onde pega o evento de click, é justamente por isto que tem este exemplo

2023-03-03 12:50 UTC, DouglasCalora commented on docs/src/pages/components/delete.md
> +Estamos utilizando nos exemplos um `custom-id` pois é necessário para conseguir utilizar os mocks de dados, **não** significa que você precisa sempre utiliza-lo para lidar com o id, na verdade na mai
Não, no comeponente QasDelete não foi alterado. O que é alterado é no plugin `Delete.js`, mas não mudei essa prop no QasDelete para não ter tantas breaking changes.

2023-03-03 13:04 UTC, DouglasCalora commented on ui/src/components/actions-menu/QasActionsMenu.vue
> +    cachedList () {
Mudei para `fullList`, é uma lista que não muda e pode ou não conter o delete adicional.

2023-03-03 13:07 UTC, eliasassuncao requested changes

2023-03-03 13:07 UTC, eliasassuncao commented on ui/src/components/delete/QasDelete.vue
> +        },
daria pra colocar na mesma linha
```js
        onDelete: isDeleting =>  this.$emit('update:deleting', isDeleting),
```

2023-03-03 13:07 UTC, eliasassuncao commented on ui/src/components/delete/QasDelete.vue
> +        },
daria pra colocar na mesma linha
```js
       onDeleteError: error =>  this.$emit('error', error),
```

2023-03-03 13:07 UTC, eliasassuncao commented on ui/src/components/delete/QasDelete.vue
>          }
daria pra colocar na mesma linha
```js
       onDeleteSuccess: response => this.$emit('success', response),
```

2023-03-03 13:08 UTC, DouglasCalora commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    },
Nosso padrão é usar `use` caso já não seja um padrão do quasar.

2023-03-03 14:22 UTC, gcarpi commented on ui/src/components/btn/QasBtn.vue
> +        ((this.icon && !this.iconRight) || (this.iconRight && !this.icon))
Deu uma bugada na minha mente aqui, mas essa condição não seria a mesma que: `this.icon || this.iconRight`? 🤔

2023-03-03 14:22 UTC, gcarpi commented on ui/src/plugins/delete/Delete.js
> +    card: { description: 'Tem certeza que deseja excluir este item?' },
Temos algumas tarefas em backlog para mudar esse texto padrão em algumas páginas, provavelmente no futuro vamos ter que conversar em essa texto ser parametrizavel

2023-03-03 19:11 UTC, DouglasCalora commented on ui/src/components/btn-dropdown/QasBtnDropdown.vue
> +    },
feito com use

2023-03-03 19:30 UTC, eliasassuncao approved these changes

2023-03-06 13:33 UTC, merged