Feature/main homolog/qas table generator sticky header
bildvitta/asteroid pull request #743
Opened 2023-03-17 18:52 UTC by gcarpi

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-03-17 19:07 UTC, gcarpi commented on ui/src/components/table-generator/QasTableGenerator.yml
> +    default: 528px
Esse é a altura que permite ser exibido 10 linhas na tabela. Foi alinhado com o time de design essa altura padrão.

2023-03-28 13:53 UTC, eliasassuncao approved these changes

2023-03-28 13:53 UTC, eliasassuncao commented on ui/src/components/table-generator/QasTableGenerator.vue
> +              background-color: #fff;
não tem uma variavel pra essa cor?

2023-03-28 13:53 UTC, eliasassuncao commented on ui/src/css/components/scrollbar.scss
> +  --scrollbar-background: #E0E0E0;
não tem variável para essa cor?

2023-03-29 12:30 UTC, gcarpi commented on ui/src/components/table-generator/QasTableGenerator.vue
> +              background-color: #fff;
Não tem, nem no Asteroid e nem no Quasar. Essa é a cor branca.

2023-03-29 15:02 UTC, eliasassuncao approved these changes

2023-03-29 18:07 UTC, DouglasCalora requested changes

2023-03-29 18:07 UTC, DouglasCalora commented on ui/src/components/table-generator/QasTableGenerator.vue
> +          }
precisa usar essa cascata?

2023-03-29 18:07 UTC, DouglasCalora commented on ui/src/css/components/scrollbar.scss
> +  border: 1px solid rgba(0%, 0%, 0%, 0%);
pq esse rgba aqui?

2023-03-29 18:07 UTC, DouglasCalora commented on ui/src/css/components/scrollbar.scss
> +  --scrollbar-background: #E0E0E0;
Não acho que ela deveria ser alterada visto que ela é tipo uma variavel do background color, de qualquer forma, todas variaveis nossas tem o prefixo `--qas-` e são definidas em `ui/src/index.scss`, principalmente se um dia poder ser personalizada.

2023-03-29 18:07 UTC, DouglasCalora commented on ui/src/components/table-generator/QasTableGenerator.vue
> +              background-color: #fff;
neste caso use `white` então.

2023-03-31 21:29 UTC, DouglasCalora approved these changes

2023-03-31 21:29 UTC, merged