QasUploader / QasSingatureUploader / QasGalleryCard / donwloadFile / QasLabel / QasFormView
bildvitta/asteroid pull request #748
Opened 2023-03-29 17:25 UTC by DouglasCalora

## Não publicado
## BREAKING CHANGES
- `QasUploader`: mudanças significativas de layout e comportamento que podem ou não gerar quebras.
- `QasUploader`: removido propriedade `hint`.
- `QasSignatureUploader`: removido propriedades `readonly`, `uploadLabel` pois agora esse controle é feito pela propriedade `uploaderProps`.

### Adicionado
- `downloadFile`: adicionado novo helper para fazer download de arquivos.
- `docs/src/components/DocPrint.vue`: adicionado novo componente para **documentação** para adicionar imagens (prints) de exemplos.
- `QasGalleryCard`: novo componente adicionado para ser utilizado no QasUploader (futuramente no QasGallery também).
- `QasSignatureUploader`: adicionado nova propriedade `uploaderProps` para repassar as propriedades para o QasUploader.
- `QasFormView`: adicionado novo evento no `window` que dispara toda vez que o submit ocorre com sucesso chamado `submit-success`.
- `QasLabel`: adicionado propriedade `color` para controle da cor com default `grey-9`.
- `QasUploader`: adicionado novas propriedades: `addButtonFn`, `addButtonLabel`, `columns`, `dialogProps`, `error`, `fields`, `formGeneratorProps`, `galleryCardProps`, `gridGeneratorProps`, e `useDownload`

### Modificado
- `QasSignatureUploader`: atualizações para se adequar as mudanças do QasUploader.
- [`QasSignatureUploader`, `QasUploader`]: adicionado ordem alfabética em métodos / data / props.
- `QasField`: atualizações para se adequar as mudanças do QasSignatureUploader.
- `QasGridGenerator`: removido logger.
- `QasUploader`: mudanças de layout e comportamento.

### Removido
- `QasSignatureUploader`: removido propriedades `readonly`, `uploadLabel` pois agora esse controle é feito pela propriedade `uploaderProps`.
- `QasUploader`: removido propriedade `hint`.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `main-homolog`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [x] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [x] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [x] Sim
- [ ] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-03-29 21:30 UTC, eliasassuncao requested changes

2023-03-29 21:30 UTC, eliasassuncao commented on docs/src/pages/components/gallery-card.md
> +Componente adaptado somente para utilização dentro do `QasUploader`.
então não seria um pv?

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/form-view/QasFormView.vue
> +        this.createSubmitSuccessEvent({ ...payload, entity: this.entity })
isso não vai deixar com mais processamento? talvez não é bom controlar via props quando criar/emitir esse evento?

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/gallery-card/QasGalleryCard.vue
> +    <header class="flat items-center no-wrap q-mb-md q-mb-xs row" :class="headerClasses">
tem dois `q-mb`

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/gallery-card/QasGalleryCard.vue
> +        <div v-if="hasActionsMenu">
precisa dessa div? não poderia utilizar o v-if direto no `qas-actions-menu` ?

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/label/QasLabel.vue
> +    },
não seria bom ter um validator `['xs', 'sm', 'md', 'lg', 'xl'].includes(margin)`

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
> +      }
quebrar linha

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/uploader/QasUploader.vue
> +          <!-- ------------------------------------ tags hidden -------------------------------------- -->
pq isso? não é somente ver as classes?

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/uploader/QasUploader.vue
> +            <div>
precisa dessa div?

2023-03-29 21:30 UTC, eliasassuncao commented on ui/src/components/uploader/QasUploader.vue
> +        name: response.files[0].name
seria melhor colocar optional chaining nesses [0] ?

2023-03-30 12:33 UTC, gcarpi commented on ui/src/components/signature-uploader/QasSignatureUploader.vue
>    <div>
Acredito que não seja necessário essa div

2023-03-30 22:15 UTC, DouglasCalora commented on docs/src/assets/menu.js
> +        name: 'downloadFile',
Esta de acordo com o nome do helper.

2023-03-30 22:15 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasFormView`: adicionado novo evento no `window` que dispara toda vez que o submit ocorre com sucesso chamado `submit-success`.
No `QasUploader` quando salvar o formulario, precisa mudar o comportamento dos cards para modo "grid".

2023-03-30 22:16 UTC, DouglasCalora commented on docs/src/pages/components/gallery-card.md
> +Componente adaptado somente para utilização dentro do `QasUploader`.
Não, no futuro vai ser usado nos modulos e no QasGallery.

2023-03-30 22:17 UTC, DouglasCalora commented on ui/src/components/form-view/QasFormView.vue
> +        this.createSubmitSuccessEvent({ ...payload, entity: this.entity })
Não é um processamento grande, talvez com o prop seja pior ainda... sem falar que toda vez que usar uploader teria que ficar passando

2023-03-30 22:24 UTC, DouglasCalora commented on ui/src/components/gallery-card/QasGalleryCard.vue
> +        <div v-if="hasActionsMenu">
mais por questão de organização.

2023-03-30 22:33 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
> +          <!-- ------------------------------------ tags hidden -------------------------------------- -->
Facilitar visualização.

2023-03-30 22:33 UTC, DouglasCalora commented on ui/src/components/label/QasLabel.vue
> +    },
feito

2023-03-30 22:34 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
> +            <div>
Sim, centralização utilizando o flex

2023-03-30 22:35 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
> +        name: response.files[0].name
Não, só é chamada essa função quando é feito o upload com sucesso.

2023-03-31 13:11 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
> +    }
Não, eu preciso sobrescrever a classe do header.

2023-03-31 13:12 UTC, DouglasCalora commented on ui/src/components/uploader/QasUploader.vue
> +    background-color: transparent;
Daria no mesmo, mas feito

2023-03-31 14:37 UTC, gcarpi commented on ui/src/components/uploader/private/PvUploaderGalleryCard.vue
> +  <div>
Mas no Vue 3 não precisa mais ter um root element

2023-03-31 14:40 UTC, eliasassuncao approved these changes

2023-03-31 22:10 UTC, merged