Feature/qas chart view
bildvitta/asteroid pull request #806
Opened 2023-06-12 17:23 UTC by gcarpi

Inclua uma pequena descrição explicando o motivo do _pull request_ e o número da _issue_ caso exista, também adicione prints caso possível.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [ ] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [ ] Adicionado | Added (novos componentes e/ou funcionalidades);
- [ ] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [ ] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [ ] Documentação
- [ ] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [ ] Não

## Checklist

- [ ] Foi discutida anteriormente com os times de Frontend e Design;
- [ ] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [ ] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [ ] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [ ] Foi atualizada e testada a documentação;
- [ ] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [ ] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-07-07 12:53 UTC, gcarpi commented on CHANGELOG.md
> +## [Não publicado]
Acho que não tem os `[]`

2023-07-07 12:53 UTC, gcarpi commented on CHANGELOG.md
> +- Componente de grafícos `QasChartView`.
graficos

2023-07-10 20:43 UTC, DouglasCalora requested changes

2023-07-10 20:43 UTC, DouglasCalora commented on app-extension/src/helpers/third-party-components-handler.js
> +      await execaSync('npm', [...command], { cwd: api.appDir })
mas ele roda o comando `install` já que removeu ele?

2023-07-10 20:43 UTC, DouglasCalora commented on docs/src/pages/components/chart-view.md
> +:::
```md
:::info
- Para renderizar múltiplos gráficos, é necessário retornar mais de um resultado no array de `results` da API.
- No gráfico abaixo, ao realizar o hover na coluna "Presencial", você verá que há um texto do tooltip customizado. Para conseguir esse resultado, é necessário passar juntamente ao objeto `data` uma chave `tooltip` com o texto customizado. Essa chave é opcional, portanto só utilize-a caso necessário.
:::
```

Será que assim não deriaxaria a tela menos poluida?

2023-07-10 20:43 UTC, DouglasCalora commented on docs/src/pages/start/develop.md
> +
remover linha

2023-07-10 20:43 UTC, DouglasCalora commented on docs/src/store/schemas/chart.js
> +export const fields = {
aplicar espaçamento nesse arquivo, seguindo o de `users`.

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    componentProps () {
parece que você vai usar isto na tag `component`, sendo que é para div, algo como `parentComponentProps`?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    chartProps () {
E se fizesse assim?
```js
chartComponent () {
  return  {
    is: this.chartType,
    props: {
      ...
    }
}

<component :is="chartComponent.is" v-bind="chartComponent.props" />
```

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    },
Cria um Enum acima:

```js
const CharTypes = {
  Bar: 'bar',
  Doughnut: 'doughnut',
  Line: 'line'
}

type: {
      default: CharTypes.Bar,
      type: String,
      validator: value => Object.values(CharTypes).includes(value)
    }
```

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +        const borderColor = this.isDoughnut ? '#FFFFFF' : colors.at(index)
precisa ser hexadecimal? `white` não resolve?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    chartFilters () {
`chartFiltersProps`

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +      return extend(true, charts[type], options)
certeza que precisa do `extend`? Testou sem? somente usando `...` ?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    },
Se não ta usando nenhuma opção de watch pq usa `handler`?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +          tooltips: this.getXAxisData(data.map(item => item.tooltip))
Aqui está fazendo 2 loops na mesma variavél, pq não utiliza apenas 1 loop?

```js
const payload = { data: [], tooltips: [] }

data.forEach(({ y, tooltip }) => {
  payload.data.push(y)
  payload.data.push(tooltip)
})
```

Dessa forma usaria apenas 1 loop

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +      const labels = this.getXAxisData(dataset.data.map(item => item.x))
```js
const labels = this.getXAxisData(dataset.data.map(({ x }) => x))
```
E um espacinho pra baixo né?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    setInitialConfig () {
esta mais para `initializeChartJS`

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +    this.setInitialConfig()
Não existe nenhuma opção para desmontar o chartjs e chamar no `unmount`, existem algumas lib que disponibilizam métodos para isto.

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.yml
> +  options:
será que não compensa ser mais especifico? Ex, no fuse passamos a prop `fuseOptions`

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/charts/bar.js
> +import { textColor } from '../defaults'
aplicar uns espaçamentos

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/charts/doughnut.js
> +function percentageFormat (value, context) {
seria `getPercentFormat`?

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/charts/doughnut.js
> +}
aplicar uns espaçamentos

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/charts/line.js
> +import { textColor } from '../defaults'
aplicar uns espaçamentos

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/plugins/legend.js
> +export const legendPluginConfig = {
aplicar uns espaçamentos

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/chart-view/config/plugins/zoom.js
> +export const zoomPluginConfig = {
aplicar uns espaçamentos

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/header-actions/QasHeaderActions.vue
> +    },
Criar Enum igual no exemplo que de acima.

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/components/header-actions/QasHeaderActions.vue
> +        'justify-between no-wrap q-col-gutter-x-md q-mb-xl row text-body1 text-grey-8',
deixa isto fixo no template

2023-07-10 20:43 UTC, DouglasCalora commented on ui/src/vue-plugin.js
> +  app.component('QasChartView', QasChartView)
Aplicar mesma logica de adicionar componente somente se declarado no `thirdPartyComponents`, igual `QasMap`.

2023-07-10 21:01 UTC, eliasassuncao commented on CHANGELOG.md
> +## [Não publicado]
feito

2023-07-10 21:01 UTC, eliasassuncao commented on CHANGELOG.md
> +## [Não publicado]
feito

2023-07-10 21:01 UTC, eliasassuncao commented on CHANGELOG.md
> +- Componente de grafícos `QasChartView`.
feito

2023-07-10 21:02 UTC, eliasassuncao commented on app-extension/src/helpers/third-party-components-handler.js
> +      await execaSync('npm', [...command], { cwd: api.appDir })
sim, na const do command já vem o `install`, por isso ficava `npm install install`

2023-07-10 21:30 UTC, eliasassuncao commented on docs/src/pages/components/chart-view.md
> +:::
feito

2023-07-10 21:31 UTC, eliasassuncao commented on docs/src/pages/start/develop.md
> +
feito

2023-07-10 21:37 UTC, eliasassuncao commented on docs/src/store/schemas/chart.js
> +export const fields = {
feito

2023-07-10 21:40 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    componentProps () {
feito

2023-07-10 21:46 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    chartProps () {
feito

2023-07-10 21:52 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    },
feito

2023-07-10 21:52 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +        const borderColor = this.isDoughnut ? '#FFFFFF' : colors.at(index)
feito

2023-07-10 21:53 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    chartFilters () {
feito

2023-07-10 21:58 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    },
feito

2023-07-10 21:59 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +      const labels = this.getXAxisData(dataset.data.map(item => item.x))
feito

2023-07-10 22:00 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    setInitialConfig () {
feito

2023-07-10 22:04 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.yml
> +  options:
passamos dessa forma quando o componente usa coisas de terceiros, exemplo `select-list` usar o `search-box`, ai seria `searchBoxProps`

2023-07-10 22:05 UTC, eliasassuncao commented on ui/src/components/chart-view/config/charts/bar.js
> +import { textColor } from '../defaults'
feito

2023-07-10 22:06 UTC, eliasassuncao commented on ui/src/components/chart-view/config/charts/doughnut.js
> +function percentageFormat (value, context) {
feito

2023-07-10 22:09 UTC, eliasassuncao commented on ui/src/components/chart-view/config/charts/doughnut.js
> +}
feito

2023-07-10 22:10 UTC, eliasassuncao commented on ui/src/components/chart-view/config/charts/line.js
> +import { textColor } from '../defaults'
feito

2023-07-10 22:10 UTC, eliasassuncao commented on ui/src/components/chart-view/config/plugins/legend.js
> +export const legendPluginConfig = {
feito

2023-07-10 22:11 UTC, eliasassuncao commented on ui/src/components/chart-view/config/plugins/zoom.js
> +export const zoomPluginConfig = {
feito

2023-07-10 22:13 UTC, eliasassuncao commented on ui/src/components/header-actions/QasHeaderActions.vue
> +    },
feito

2023-07-10 22:14 UTC, eliasassuncao commented on ui/src/components/header-actions/QasHeaderActions.vue
> +        'justify-between no-wrap q-col-gutter-x-md q-mb-xl row text-body1 text-grey-8',
feito

2023-07-10 22:17 UTC, eliasassuncao commented on ui/src/vue-plugin.js
> +  app.component('QasChartView', QasChartView)
feito

2023-07-11 12:48 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +          tooltips: this.getXAxisData(data.map(item => item.tooltip))
feito

2023-07-11 13:03 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +    this.setInitialConfig()
feito

2023-07-11 13:47 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.yml
> +  options:
Mas são coisas diferentes, `props` é para propriedade de componente, neste caso é configuração de lib, talvez algo como `chartJSOptions`, mas acho que pode ser options...

2023-07-11 13:53 UTC, DouglasCalora requested changes

2023-07-11 13:53 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +const CharTypes = {
`ChartTypes`, escrevi errado

2023-07-11 13:53 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
> +      const labels = this.getXAxisData(dataset.data.map(item => item.x))
Continua sem

2023-07-11 13:53 UTC, DouglasCalora commented on ui/src/components/header-actions/QasHeaderActions.vue
>        default: 'center',
`AlignTypes.Center`

2023-07-11 13:53 UTC, DouglasCalora commented on ui/src/vue-plugin.js
> -  app.component('QasChartView', QasChartView)
removeu o import também?

2023-07-11 13:53 UTC, DouglasCalora commented on ui/src/components/chart-view/QasChartView.vue
>        default: 'bar',
`ChartTypes.Bar`

2023-07-11 15:01 UTC, eliasassuncao commented on ui/src/vue-plugin.js
> -  app.component('QasChartView', QasChartView)
feito

2023-07-11 15:02 UTC, eliasassuncao commented on ui/src/components/header-actions/QasHeaderActions.vue
>        default: 'center',
feito

2023-07-11 15:11 UTC, eliasassuncao commented on ui/src/components/chart-view/QasChartView.vue
> +      const labels = this.getXAxisData(dataset.data.map(item => item.x))
- destruction do x fica estranho e confuso, mantive o item.x
- foi feito o espaço sim. 
![image](https://github.com/bildvitta/asteroid/assets/29342573/c872f10c-e45c-4f66-958b-2d9a59d55e7b)

2023-07-11 16:21 UTC, DouglasCalora approved these changes

2023-07-11 16:21 UTC, merged