Changes in QasInput/QasLabel/QasNumericInput/QasField
bildvitta/asteroid pull request #879
Opened 2023-08-21 17:03 UTC by DouglasCalora

## Não publicado
### Adicionado
- [`QasLabel`, `QasSelect`, `QasInput`, `QasNumericInput`]: adicionado propriedade `required` para controle de label obrigatória.
- Adicionado novo helper `getRequiredLabel` para retornar label obrigatória normalizada.

### Modificado
- [`QasNumericInput`, `QasSelect`]: adicionado propriedade `label` fixo no componente e não mais pelo `$attrs` para funcionar logica do required.
- `QasField`: agora logica de label obrigatória é controlada em cada componente e não mais pelo QasLabel.

## Versão do asteroid

- [ ] v2 -> a partir da branch `v2`.
- [x] v3-beta.x -> a partir da branch `develop`.
- [ ] v3-stable -> a partir da branch `main`.

## Tipo de alteração

- [x] Adicionado | Added (novos componentes e/ou funcionalidades);
- [x] Modificado | Changed (alterações que podem ou não conter _breaking changes_);
- [ ] Corrigido | Fixed (correção de bugs, typos, etc);
- [ ] Removido | removed (remoção de algum componente e/ou funcionalidade).

## O que foi alterado/adicionado

- [ ] CSS
- [x] Componentes
- [ ] Composables (v3)
- [ ] Diretivas
- [x] Documentação
- [x] Helpers
- [ ] Mixins
- [ ] Paginas
- [ ] Plugins
- [ ] Testes
- [ ] Outros

Este _pull request_ introduz algum _breaking change_?

- [ ] Sim
- [x] Não

## Checklist

- [x] Foi discutida anteriormente com os times de Frontend e Design;
- [x] Foi testado manualmente no ambiente de desenvolvimento (`/docs` se v3 ou `ui/dev` se v2);
- [x] Foi constatado que esta modificação não gerou erros ou alertas no Console;
- [x] Foi verificado se o código segue os padrões de escrita e validado com o ESLint;
- [ ] Foi escrito teste automatizado;
- [x] Foi atualizada e testada a documentação;
- [x] Foi atualizado o _changelog_ seguindo o padrão "Keep a Changelog";
- [x] Fiz meu próprio _code review_ antes de abrir este _pull request_.

2023-08-21 17:54 UTC, eliasassuncao approved these changes

2023-08-21 17:54 UTC, eliasassuncao commented on docs/src/examples/QasSelect/Required.vue
> +    </div>
precisa dessa div?

2023-08-21 17:54 UTC, eliasassuncao commented on ui/src/components/input/QasInput.vue
> +    requiredLabel () {
acho estranho esse nome, nem sempre vai ser um `required label`. um `getFormattedLabel` não seria melhor?

2023-08-21 17:54 UTC, eliasassuncao commented on ui/src/components/numeric-input/QasNumericInput.vue
> +  <q-field :label="requiredLabel" :model-value="modelValue" outlined>
o mesmo aqui

2023-08-21 18:06 UTC, gcarpi requested changes

2023-08-21 18:06 UTC, gcarpi commented on ui/src/components/input/QasInput.vue
> +    requiredLabel () {
Concordo, talvez `formattedLabel` seria o melhor... não costumamos usar `get` em computadas

2023-08-21 22:43 UTC, DouglasCalora commented on docs/src/examples/QasSelect/Required.vue
> +    </div>
E como estamos fazendo sempre na doc, sempre que existe mais de 1 linha englobamos em uma div.

2023-08-21 22:45 UTC, DouglasCalora commented on ui/src/components/input/QasInput.vue
> +    requiredLabel () {
respondido no discord.

2023-08-21 22:45 UTC, DouglasCalora commented on CHANGELOG.md
> +- `QasField`: agora logica de label obrigatória é controlada em cada componente e não mais pelo QasLabel.
Feito.

2023-08-22 12:20 UTC, DouglasCalora commented on ui/src/components/select/QasSelect.vue
> +    requiredLabel () {
Alterado para `formattedLabel`.

2023-08-22 12:23 UTC, gcarpi approved these changes

2023-08-22 12:25 UTC, merged